//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("AccountTypeBankCode", Namespace="urn:org:ebics:H004")]
    public partial class AccountTypeBankCode
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// <para xml:lang="en">Maximum length: 11.</para>
        /// <para xml:lang="en">Pattern: \d{8}|([A-Z]{6}[A-Z0-9]{2}([A-Z0-9]{3})?).</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _international = false;
        
        /// <summary>
        /// <para xml:lang="en">Is the bank code specified using the national=German or the international SWIFT-BIC format?</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlAttributeAttribute("international")]
        public bool International
        {
            get
            {
                return _international;
            }
            set
            {
                _international = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">National=German prefix for bank codes.</para>
        /// <para xml:lang="en">Minimum length: 2. Maximum length: 2.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("Prefix")]
        public string Prefix { get; set; }
    }
}
