//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    /// <summary>
    /// <para xml:lang="en">Data type for address information with regard to distributed signature (order types HKD, HTD).</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("AddressInfoType", Namespace="urn:org:ebics:H004")]
    public partial class AddressInfoType
    {
        
        /// <summary>
        /// <para xml:lang="en">Customer's name.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public string Name { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Street and house number.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Street")]
        public string Street { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Postal code.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("PostCode")]
        public string PostCode { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">City.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("City")]
        public string City { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Region / province / federal state.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Region")]
        public string Region { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Country.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Country")]
        public string Country { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="AddressInfoType" /> class.</para>
        /// </summary>
        public AddressInfoType()
        {
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
    }
}
