//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("AmountType", Namespace="urn:org:ebics:H004")]
    public partial class AmountType
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// <para xml:lang="en">Total number of digits: 24.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 4.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _currency = "EUR";
        
        /// <summary>
        /// <para xml:lang="en">Currency code, default setting is "EUR".</para>
        /// <para xml:lang="en">Minimum length: 3. Maximum length: 3.</para>
        /// <para xml:lang="en">Pattern: [A-Z]{3}.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute("EUR")]
        [System.Xml.Serialization.XmlAttributeAttribute("Currency")]
        public string Currency
        {
            get
            {
                return _currency;
            }
            set
            {
                _currency = value;
            }
        }
    }
}
