//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("AttributedAccountTypeNationalBankCode", Namespace="urn:org:ebics:H004")]
    public partial class AttributedAccountTypeNationalBankCode
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Role of the bank during the transaction.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("Role")]
        public BankCodeRoleType Role { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Textual description of the role the account place during the transaction; use only if the corresponding 'role' field is set to 'other'.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("Description")]
        public string Description { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Format identification.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("format")]
        public string Format { get; set; }
    }
}
