//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("AttributedAccountType", Namespace="urn:org:ebics:H004")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EBICO.Core.Schema.H004.HvtAccountInfoType))]
    public partial class AttributedAccountType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AttributedAccountTypeAccountNumber> _accountNumber;
        
        /// <summary>
        /// <para xml:lang="en">Kontonummer (Account number (German format and/or international = IBAN).</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("AccountNumber")]
        public System.Collections.ObjectModel.Collection<AttributedAccountTypeAccountNumber> AccountNumber
        {
            get
            {
                return _accountNumber;
            }
            private set
            {
                _accountNumber = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AccountNumber collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccountNumberSpecified
        {
            get
            {
                return (this.AccountNumber.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="AttributedAccountType" /> class.</para>
        /// </summary>
        public AttributedAccountType()
        {
            this._accountNumber = new System.Collections.ObjectModel.Collection<AttributedAccountTypeAccountNumber>();
            this._nationalAccountNumber = new System.Collections.ObjectModel.Collection<AttributedAccountTypeNationalAccountNumber>();
            this._bankCode = new System.Collections.ObjectModel.Collection<AttributedAccountTypeBankCode>();
            this._nationalBankCode = new System.Collections.ObjectModel.Collection<AttributedAccountTypeNationalBankCode>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AttributedAccountTypeNationalAccountNumber> _nationalAccountNumber;
        
        /// <summary>
        /// <para xml:lang="en">Account in free format.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("NationalAccountNumber")]
        public System.Collections.ObjectModel.Collection<AttributedAccountTypeNationalAccountNumber> NationalAccountNumber
        {
            get
            {
                return _nationalAccountNumber;
            }
            private set
            {
                _nationalAccountNumber = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the NationalAccountNumber collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NationalAccountNumberSpecified
        {
            get
            {
                return (this.NationalAccountNumber.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AttributedAccountTypeBankCode> _bankCode;
        
        /// <summary>
        /// <para xml:lang="en">Bank code (German and/or international=SWIFT-BIC).</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("BankCode")]
        public System.Collections.ObjectModel.Collection<AttributedAccountTypeBankCode> BankCode
        {
            get
            {
                return _bankCode;
            }
            private set
            {
                _bankCode = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the BankCode collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BankCodeSpecified
        {
            get
            {
                return (this.BankCode.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AttributedAccountTypeNationalBankCode> _nationalBankCode;
        
        /// <summary>
        /// <para xml:lang="en">Bank code in free format.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("NationalBankCode")]
        public System.Collections.ObjectModel.Collection<AttributedAccountTypeNationalBankCode> NationalBankCode
        {
            get
            {
                return _nationalBankCode;
            }
            private set
            {
                _nationalBankCode = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the NationalBankCode collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NationalBankCodeSpecified
        {
            get
            {
                return (this.NationalBankCode.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("AccountHolder")]
        public AttributedAccountTypeAccountHolder AccountHolder { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _currency = "EUR";
        
        /// <summary>
        /// <para xml:lang="en">Currency code for this account, Default=EUR.</para>
        /// <para xml:lang="en">Minimum length: 3. Maximum length: 3.</para>
        /// <para xml:lang="en">Pattern: [A-Z]{3}.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute("EUR")]
        [System.Xml.Serialization.XmlAttributeAttribute("Currency")]
        public string Currency
        {
            get
            {
                return _currency;
            }
            set
            {
                _currency = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Description of this account.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("Description")]
        public string Description { get; set; }
    }
}
