//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("CurrencyCode", Namespace="urn:org:ebics:H004")]
    public enum CurrencyCode
    {
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("AFN")]
        Afn,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("ALL")]
        All,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("AMD")]
        Amd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("ANG")]
        Ang,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("AOA")]
        Aoa,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("ARS")]
        Ars,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("AUD")]
        Aud,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("AWG")]
        Awg,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("AZM")]
        Azm,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("BAM")]
        Bam,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("BBD")]
        Bbd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("BDT")]
        Bdt,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("BGN")]
        Bgn,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("BHD")]
        Bhd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("BMD")]
        Bmd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("BND")]
        Bnd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("BOB")]
        Bob,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("BRL")]
        Brl,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("BSD")]
        Bsd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("BTN")]
        Btn,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("BWP")]
        Bwp,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("BYR")]
        Byr,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("BZD")]
        Bzd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("CAD")]
        Cad,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("CDF")]
        Cdf,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("CHF")]
        Chf,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("CLP")]
        Clp,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("CNY")]
        Cny,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("COP")]
        Cop,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("CRC")]
        Crc,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("CSD")]
        Csd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("CUP")]
        Cup,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("CVE")]
        Cve,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("CYP")]
        Cyp,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("CZK")]
        Czk,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("DJV")]
        Djv,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("DKK")]
        Dkk,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("DOP")]
        Dop,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("DZD")]
        Dzd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("ECS")]
        Ecs,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("EEK")]
        Eek,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("EGP")]
        Egp,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("ETB")]
        Etb,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("EUR")]
        Eur,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("FJD")]
        Fjd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("FKP")]
        Fkp,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("GBP")]
        Gbp,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("GEL")]
        Gel,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("GHC")]
        Ghc,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("GIP")]
        Gip,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("GMD")]
        Gmd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("GNF")]
        Gnf,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("GTQ")]
        Gtq,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("GYD")]
        Gyd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("HKD")]
        Hkd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("HNL")]
        Hnl,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("HRK")]
        Hrk,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("HTG")]
        Htg,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("HUF")]
        Huf,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("IDR")]
        Idr,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("ILS")]
        Ils,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("INR")]
        Inr,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("IQD")]
        Iqd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("IRR")]
        Irr,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("ISK")]
        Isk,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("JMD")]
        Jmd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("JOD")]
        Jod,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("JPY")]
        Jpy,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("KES")]
        Kes,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("KGS")]
        Kgs,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("KHR")]
        Khr,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("KMF")]
        Kmf,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("KPW")]
        Kpw,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("KRW")]
        Krw,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("KWD")]
        Kwd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("KYD")]
        Kyd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("KZT")]
        Kzt,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("LAK")]
        Lak,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("LBP")]
        Lbp,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("LKR")]
        Lkr,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("LRD")]
        Lrd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("LSL")]
        Lsl,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("LTL")]
        Ltl,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("LVL")]
        Lvl,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("LYD")]
        Lyd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("MAD")]
        Mad,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("MDL")]
        Mdl,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("MGF")]
        Mgf,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("MKD")]
        Mkd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("MMK")]
        Mmk,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("MNT")]
        Mnt,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("MOP")]
        Mop,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("MRO")]
        Mro,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("MTL")]
        Mtl,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("MUR")]
        Mur,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("MVR")]
        Mvr,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("MWK")]
        Mwk,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("MXN")]
        Mxn,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("MYR")]
        Myr,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("MZM")]
        Mzm,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("NAD")]
        Nad,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("NGN")]
        Ngn,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("NIO")]
        Nio,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("NOK")]
        Nok,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("NPR")]
        Npr,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("NZD")]
        Nzd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("OMR")]
        Omr,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("PAB")]
        Pab,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("PEN")]
        Pen,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("PGK")]
        Pgk,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("PHP")]
        Php,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("PKR")]
        Pkr,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("PLN")]
        Pln,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("PYG")]
        Pyg,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("QAR")]
        Qar,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("ROL")]
        Rol,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("RUB")]
        Rub,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("RWF")]
        Rwf,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("SAR")]
        Sar,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("SBD")]
        Sbd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("SCR")]
        Scr,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("SDD")]
        Sdd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("SEK")]
        Sek,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("SGD")]
        Sgd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("SHP")]
        Shp,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("SIT")]
        Sit,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("SKK")]
        Skk,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("SLL")]
        Sll,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("SOS")]
        Sos,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("SRD")]
        Srd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("STD")]
        Std,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("SVC")]
        Svc,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("SYP")]
        Syp,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("SZL")]
        Szl,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("THB")]
        Thb,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("TJS")]
        Tjs,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("TMM")]
        Tmm,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("TND")]
        Tnd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("TOP")]
        Top,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("TRL")]
        Trl,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("TRY")]
        Try,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("TTD")]
        Ttd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("TWD")]
        Twd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("TZS")]
        Tzs,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("UAH")]
        Uah,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("UGX")]
        Ugx,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("USD")]
        Usd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("UYU")]
        Uyu,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("UZS")]
        Uzs,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("VEB")]
        Veb,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("VND")]
        Vnd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("VUV")]
        Vuv,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("WST")]
        Wst,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("XAF")]
        Xaf,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("XCD")]
        Xcd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("XOF")]
        Xof,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("XPF")]
        Xpf,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("XTS")]
        Xts,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("XXX")]
        Xxx,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("YER")]
        Yer,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("ZAR")]
        Zar,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("ZMK")]
        Zmk,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("ZWD")]
        Zwd,
    }
}
