//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("EbicsResponseHeader", Namespace="urn:org:ebics:H004", AnonymousType=true)]
    public partial class EbicsResponseHeader : EBICO.Core.Schema.H004.IAuthenticationMarker
    {
        
        /// <summary>
        /// <para xml:lang="en">contains the static header entries.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("static")]
        public ResponseStaticHeaderType Static { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">contains the mutable header entries.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("mutable")]
        public ResponseMutableHeaderType Mutable { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _authenticate = true;
        
        /// <summary>
        /// <para xml:lang="en">The element (and its substructures) that belongs to this attribute is to be authenticated.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("authenticate")]
        public bool Authenticate
        {
            get
            {
                return _authenticate;
            }
            set
            {
                _authenticate = value;
            }
        }
    }
}
