//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("EbicsUnsignedRequestBody", Namespace="urn:org:ebics:H004", AnonymousType=true)]
    public partial class EbicsUnsignedRequestBody
    {
        
        /// <summary>
        /// <para xml:lang="en">Transfer of order data and the ESs.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("DataTransfer")]
        public EbicsUnsignedRequestBodyDataTransfer DataTransfer { get; set; }
    }
}
