//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("EbicsRequestBody", Namespace="urn:org:ebics:H004", AnonymousType=true)]
    public partial class EbicsRequestBody
    {
        
        /// <summary>
        /// <para xml:lang="en">Data sent for pre-validation; mandatory for initialisation phase during uploads using order attribute OZH (order signature(s) + order data).</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("PreValidation")]
        public EbicsRequestBodyPreValidation PreValidation { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Transfer of signature or order data; mandatory for uploads only.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("DataTransfer")]
        public EBICO.Core.Schema.H004.DataTransferRequestType DataTransfer { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Receipt of transfer.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("TransferReceipt")]
        public EbicsRequestBodyTransferReceipt TransferReceipt { get; set; }
    }
}
