//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("EbicsResponseBody", Namespace="urn:org:ebics:H004", AnonymousType=true)]
    public partial class EbicsResponseBody
    {
        
        /// <summary>
        /// <para xml:lang="en">Transfer of signature or order data; mandatory for downloads only.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("DataTransfer")]
        public EBICO.Core.Schema.H004.DataTransferResponseType DataTransfer { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">order-related return code of the previous request.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ReturnCode")]
        public EbicsResponseBodyReturnCode ReturnCode { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">timestamp indicating the latest update of the bank parameters; may be set during initialisation phase only.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("TimestampBankParameter")]
        public EbicsResponseBodyTimestampBankParameter TimestampBankParameter { get; set; }
    }
}
