//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    /// <summary>
    /// <para xml:lang="en">Data type for encryption key.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("EncryptionCertificateInfoType", Namespace="urn:org:ebics:H004")]
    public partial class EncryptionCertificateInfoType : CertificateInfoType
    {
        
        /// <summary>
        /// <para xml:lang="en">Encryption Version.</para>
        /// <para xml:lang="en">Pattern: E\d{3}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("EncryptionVersion")]
        public string EncryptionVersion { get; set; }
    }
}
