//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("FileFormatType", Namespace="urn:org:ebics:H004")]
    public partial class FileFormatType
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">ISO-Code to identify the country (EU for Europe)</para>
        /// <para xml:lang="en">ISO-Code to identify the country.</para>
        /// <para xml:lang="en">Minimum length: 2. Maximum length: 2.</para>
        /// <para xml:lang="en">Pattern: [A-Z]{2,2}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("CountryCode")]
        public string CountryCode { get; set; }
    }
}
