//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    /// <summary>
    /// <para xml:lang="en">Order type for order data H3K (request: initialise all three user's keys).</para>
    /// <para xml:lang="en">Order data for order type H3K (request: initialise all three user's keys).</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("H3KRequestOrderDataType", Namespace="urn:org:ebics:H004")]
    [System.Xml.Serialization.XmlRootAttribute("H3KRequestOrderData", Namespace="urn:org:ebics:H004")]
    public partial class H3KRequestOrderDataType
    {
        
        /// <summary>
        /// <para xml:lang="en">Key for electronic Signature</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("SignatureCertificateInfo")]
        public EBICO.Core.Schema.H004.SignatureCertificateInfoType SignatureCertificateInfo { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Authentication key</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("AuthenticationCertificateInfo")]
        public EBICO.Core.Schema.H004.AuthenticationCertificateInfoType AuthenticationCertificateInfo { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Encryption key</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("EncryptionCertificateInfo")]
        public EBICO.Core.Schema.H004.EncryptionCertificateInfoType EncryptionCertificateInfo { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">PartnerID.</para>
        /// <para xml:lang="en">Maximum length: 35.</para>
        /// <para xml:lang="en">Pattern: [a-zA-Z0-9,=]{1,35}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("PartnerID")]
        public string PartnerId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">UserID.</para>
        /// <para xml:lang="en">Maximum length: 35.</para>
        /// <para xml:lang="en">Pattern: [a-zA-Z0-9,=]{1,35}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("UserID")]
        public string UserId { get; set; }
    }
}
