//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    /// <summary>
    /// <para xml:lang="en">Order data for order type HPB (response: receive bank's public keys).</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("HPBResponseOrderDataType", Namespace="urn:org:ebics:H004")]
    [System.Xml.Serialization.XmlRootAttribute("HPBResponseOrderData", Namespace="urn:org:ebics:H004")]
    public partial class HpbResponseOrderDataType
    {
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("AuthenticationPubKeyInfo")]
        public EBICO.Core.Schema.H004.AuthenticationPubKeyInfoType AuthenticationPubKeyInfo { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("EncryptionPubKeyInfo")]
        public EBICO.Core.Schema.H004.EncryptionPubKeyInfoType EncryptionPubKeyInfo { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 35.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("HostID")]
        public string HostId { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="HpbResponseOrderDataType" /> class.</para>
        /// </summary>
        public HpbResponseOrderDataType()
        {
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
    }
}
