//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("HPDAccessParamsType", Namespace="urn:org:ebics:H004")]
    public partial class HpdAccessParamsType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<HpdAccessParamsTypeUrl> _url;
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("URL")]
        public System.Collections.ObjectModel.Collection<HpdAccessParamsTypeUrl> Url
        {
            get
            {
                return _url;
            }
            private set
            {
                _url = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="HpdAccessParamsType" /> class.</para>
        /// </summary>
        public HpdAccessParamsType()
        {
            this._url = new System.Collections.ObjectModel.Collection<HpdAccessParamsTypeUrl>();
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 80.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Institute")]
        public string Institute { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 35.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("HostID")]
        public string HostId { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
    }
}
