//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    /// <summary>
    /// <para xml:lang="en">Data type for HPD's parameters regarding the EBICS protocol.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("HPDProtocolParamsType", Namespace="urn:org:ebics:H004")]
    public partial class HpdProtocolParamsType
    {
        
        /// <summary>
        /// <para xml:lang="en">Specification of supported versions..</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Version")]
        public HpdVersionType Version { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Parameter denoting the recovery function (recovery of aborted transmissions).</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Recovery")]
        public HpdProtocolParamsTypeRecovery Recovery { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Parameter denoting the pre-validation (beyond transmission of signatures).</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("PreValidation")]
        public HpdProtocolParamsTypePreValidation PreValidation { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Parameter denoting the X.509 functionality.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("X509Data")]
        public HpdProtocolParamsTypeX509Data X509Data { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Parameter denoting the download of customer and user data (order types HKD/HTD).</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ClientDataDownload")]
        public HpdProtocolParamsTypeClientDataDownload ClientDataDownload { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Parameter denoting the reception of order types which provides downloadable order data (order type HAA).</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("DownloadableOrderData")]
        public HpdProtocolParamsTypeDownloadableOrderData DownloadableOrderData { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="HpdProtocolParamsType" /> class.</para>
        /// </summary>
        public HpdProtocolParamsType()
        {
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
    }
}
