//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("HVTOrderFlagsType", Namespace="urn:org:ebics:H004")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HvtOrderParamsTypeOrderFlags))]
    public partial class HvtOrderFlagsType
    {
        
        /// <summary>
        /// <para xml:lang="en">Are the transaction details so be transmitted as particular order content information requested for display matters or in complete order data file form? (Proposal for Default=false)</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("completeOrderData")]
        public bool CompleteOrderData { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Limit for the transaction details to be transmitted; if completeOrderData=false, maximum number of details of a particular order; 0 for unlimited number of details (Proposal for Default=100).</para>
        /// <para xml:lang="en">Total number of digits: 10.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("fetchLimit")]
        public ulong FetchLimit { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Offset position in the original order file which marks the starting point for the transaction details to be transmitted; applies to the sequential number of a particular order if completeOrderData=false (Proposal for Default=0).</para>
        /// <para xml:lang="en">Total number of digits: 10.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("fetchOffset")]
        public ulong FetchOffset { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.XmlAttribute> _anyAttribute;
        
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="HvtOrderFlagsType" /> class.</para>
        /// </summary>
        public HvtOrderFlagsType()
        {
            this._anyAttribute = new System.Collections.ObjectModel.Collection<System.Xml.XmlAttribute>();
        }
    }
}
