//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("HVZOrderDetailsType", Namespace="urn:org:ebics:H004")]
    public partial class HvzOrderDetailsType : IHvzPaymentOrderDetailsStructure
    {
        
        /// <summary>
        /// <para xml:lang="en">Type of the order.</para>
        /// <para xml:lang="en">Minimum length: 3. Maximum length: 3.</para>
        /// <para xml:lang="en">Pattern: [A-Z0-9]{3}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderType")]
        public string OrderType { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Identification of the file format in the case of FUL/FDL</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("FileFormat")]
        public EBICO.Core.Schema.H004.FileFormatType FileFormat { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">ID number of the order.</para>
        /// <para xml:lang="en">Minimum length: 4. Maximum length: 4.</para>
        /// <para xml:lang="en">Pattern: [A-Z][A-Z0-9]{3}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderID")]
        public string OrderId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Hash value of the order data.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("DataDigest")]
        public EBICO.Core.Schema.H004.DataDigestType DataDigest { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Can the order file be downloaded in the original format? (HVT with completeOrderData=true)</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderDataAvailable")]
        public bool OrderDataAvailable { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Size of uncompressed order data in Bytes.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderDataSize")]
        public string OrderDataSize { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Can the order details be downloaded as XML document HVTResponseOrderData?  (HVT with completeOrderData=false)</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderDetailsAvailable")]
        public bool OrderDetailsAvailable { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Total transaction number for all logical files (from dispay file).</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("TotalOrders")]
        public string TotalOrders { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Total transaction amount for all logical files (from dispay file).</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("TotalAmount")]
        public HvzPaymentOrderDetailsStructureTotalAmount TotalAmount { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Order currency (only if identical across all transactions, ship otherwise).</para>
        /// <para xml:lang="en">Minimum length: 3. Maximum length: 3.</para>
        /// <para xml:lang="en">Pattern: [A-Z]{3}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Currency")]
        public string Currency { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Order details from display file for first logical file.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("FirstOrderInfo")]
        public HvzPaymentOrderDetailsStructureFirstOrderInfo FirstOrderInfo { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Information regarding the signing modalities of the order.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("SigningInfo")]
        public HvuSigningInfoType SigningInfo { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<SignerInfoType> _signerInfo;
        
        /// <summary>
        /// <para xml:lang="en">Information regarding the users who already signed the order.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("SignerInfo")]
        public System.Collections.ObjectModel.Collection<SignerInfoType> SignerInfo
        {
            get
            {
                return _signerInfo;
            }
            private set
            {
                _signerInfo = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the SignerInfo collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SignerInfoSpecified
        {
            get
            {
                return (this.SignerInfo.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="HvzOrderDetailsType" /> class.</para>
        /// </summary>
        public HvzOrderDetailsType()
        {
            this._signerInfo = new System.Collections.ObjectModel.Collection<SignerInfoType>();
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
        
        /// <summary>
        /// <para xml:lang="en">Information regarding the originator of the order.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OriginatorInfo")]
        public HvuOriginatorInfoType OriginatorInfo { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
    }
}
