//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    /// <summary>
    /// <para xml:lang="en">Marker for elements and their substructures that are to be authenticated.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    public partial interface IAuthenticationMarker
    {
        
        /// <summary>
        /// <para xml:lang="en">The element (and its substructures) that belongs to this attribute is to be authenticated.</para>
        /// </summary>
        bool Authenticate
        {
            get;
            set;
        }
    }
}
