//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    /// <summary>
    /// <para xml:lang="en">optional support flag, default = true.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    public partial interface IOptSupportFlag
    {
        
        /// <summary>
        /// <para xml:lang="en">Is this function supported?</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(true)]
        bool Supported
        {
            get;
            set;
        }
    }
}
