//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("OrderTType", Namespace="urn:org:ebics:H004")]
    public enum OrderTType
    {
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("HSA")]
        Hsa,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("HIA")]
        Hia,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("HPB")]
        Hpb,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("HCA")]
        Hca,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("HPD")]
        Hpd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("HVU")]
        Hvu,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("HVD")]
        Hvd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("HVT")]
        Hvt,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("HVE")]
        Hve,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("HVS")]
        Hvs,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("HKD")]
        Hkd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("HAA")]
        Haa,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("AAE")]
        Aae,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("AEA")]
        Aea,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("AIA")]
        Aia,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("AKA")]
        Aka,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("AWV")]
        Awv,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("AZM")]
        Azm,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("AZV")]
        Azv,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("AZ2")]
        Az2,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("AZ4")]
        Az4,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("DDG")]
        Ddg,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("DHB")]
        Dhb,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("DTE")]
        Dte,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("DTI")]
        Dti,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("DTM")]
        Dtm,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("DTV")]
        Dtv,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("DT2")]
        Dt2,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("DT4")]
        Dt4,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("EAB")]
        Eab,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("ECS")]
        Ecs,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("EDC")]
        Edc,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("EEA")]
        Eea,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("EEZ")]
        Eez,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("EIB")]
        Eib,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("EIK")]
        Eik,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("ESA")]
        Esa,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("ESM")]
        Esm,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("ESR")]
        Esr,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("ESZ")]
        Esz,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("ESU")]
        Esu,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("EUE")]
        Eue,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("GAB")]
        Gab,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("GAK")]
        Gak,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("GKT")]
        Gkt,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("IDD")]
        Idd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("IIB")]
        Iib,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("IIK")]
        Iik,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("INT")]
        Int,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("IZG")]
        Izg,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("IZL")]
        Izl,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("IZV")]
        Izv,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("MAO")]
        Mao,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("MCV")]
        Mcv,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("MC2")]
        Mc2,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("MC4")]
        Mc4,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("POZ")]
        Poz,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("RDT")]
        Rdt,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("RFT")]
        Rft,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("STA")]
        Sta,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("VMK")]
        Vmk,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("WPA")]
        Wpa,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("WPB")]
        Wpb,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("WPC")]
        Wpc,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("WPD")]
        Wpd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("INI")]
        Ini,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("PTK")]
        Ptk,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("PUB")]
        Pub,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("SPR")]
        Spr,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("VPB")]
        Vpb,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("FIN")]
        Fin,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("IZS")]
        Izs,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("SSP")]
        Ssp,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("ATA")]
        Ata,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("BKA")]
        Bka,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("BZK")]
        Bzk,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("DKI")]
        Dki,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("DMI")]
        Dmi,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("DSW")]
        Dsw,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("ESG")]
        Esg,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("ESP")]
        Esp,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("FTB")]
        Ftb,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("FTD")]
        Ftd,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("IBK")]
        Ibk,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("IBW")]
        Ibw,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("IBU")]
        Ibu,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("IKK")]
        Ikk,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("IKU")]
        Iku,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("IKW")]
        Ikw,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("KTH")]
        Kth,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("KTR")]
        Ktr,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("KKZ")]
        Kkz,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("TST")]
        Tst,
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("UPD")]
        Upd,
    }
}
