//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("OrderDetailsType", Namespace="urn:org:ebics:H004")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NoPubKeyDigestsReqOrderDetailsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnsecuredReqOrderDetailsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnsignedReqOrderDetailsType))]
    public abstract partial class OrderDetailsType
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 3. Maximum length: 3.</para>
        /// <para xml:lang="en">Pattern: [A-Z0-9]{3}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderType")]
        public string OrderType { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 5. Maximum length: 5.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderAttribute")]
        public string OrderAttribute { get; set; }
    }
}
