//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    /// <summary>
    /// <para xml:lang="en">Generic key value parameters.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("Parameter", Namespace="urn:org:ebics:H004", AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute("Parameter", Namespace="urn:org:ebics:H004")]
    public partial class Parameter
    {
        
        /// <summary>
        /// <para xml:lang="en">Name of the parameter (= key).</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public string Name { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Value of the parameter.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public ParameterValue Value { get; set; }
    }
}
