//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("PartnerInfoTypeAccountInfo", Namespace="urn:org:ebics:H004")]
    public partial class PartnerInfoTypeAccountInfo : EBICO.Core.Schema.H004.AccountType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _usageOrderTypes;
        
        /// <summary>
        /// <para xml:lang="en">List containing the order types which contain this account is restricted to; if omitted, the account is unrestricted; if the list is empty the account is blocked for any order type.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("UsageOrderTypes")]
        public System.Collections.ObjectModel.Collection<string> UsageOrderTypes
        {
            get
            {
                return _usageOrderTypes;
            }
            private set
            {
                _usageOrderTypes = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the UsageOrderTypes collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UsageOrderTypesSpecified
        {
            get
            {
                return (this.UsageOrderTypes.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PartnerInfoTypeAccountInfo" /> class.</para>
        /// </summary>
        public PartnerInfoTypeAccountInfo()
        {
            this._usageOrderTypes = new System.Collections.ObjectModel.Collection<string>();
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 64.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("ID")]
        public string Id { get; set; }
    }
}
