//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    /// <summary>
    /// <para xml:lang="en">Data type for customer data with regard to distributed signatures (order types HKD, HTD).</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("PartnerInfoType", Namespace="urn:org:ebics:H004")]
    public partial class PartnerInfoType
    {
        
        /// <summary>
        /// <para xml:lang="en">Information about the customer's adress.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("AddressInfo")]
        public AddressInfoType AddressInfo { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Information about the customer's banking access paramters.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("BankInfo")]
        public BankInfoType BankInfo { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PartnerInfoTypeAccountInfo> _accountInfo;
        
        /// <summary>
        /// <para xml:lang="en">Information about the customer's accounts.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("AccountInfo")]
        public System.Collections.ObjectModel.Collection<PartnerInfoTypeAccountInfo> AccountInfo
        {
            get
            {
                return _accountInfo;
            }
            private set
            {
                _accountInfo = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AccountInfo collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccountInfoSpecified
        {
            get
            {
                return (this.AccountInfo.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PartnerInfoType" /> class.</para>
        /// </summary>
        public PartnerInfoType()
        {
            this._accountInfo = new System.Collections.ObjectModel.Collection<PartnerInfoTypeAccountInfo>();
            this._orderInfo = new System.Collections.ObjectModel.Collection<AuthOrderInfoType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AuthOrderInfoType> _orderInfo;
        
        /// <summary>
        /// <para xml:lang="en">Information about order types which the customer is authorised to use.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderInfo")]
        public System.Collections.ObjectModel.Collection<AuthOrderInfoType> OrderInfo
        {
            get
            {
                return _orderInfo;
            }
            private set
            {
                _orderInfo = value;
            }
        }
    }
}
