//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("PubKeyInfoType", Namespace="urn:org:ebics:H004")]
    [System.Xml.Serialization.XmlRootAttribute("PubKeyInfoType", Namespace="urn:org:ebics:H004")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuthenticationPubKeyInfoType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EncryptionPubKeyInfoType))]
    public partial class PubKeyInfoType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("X509Data", Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public EBICO.Core.Schema.XmlDsig.X509DataType X509Data { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("PubKeyValue")]
        public PubKeyValueType PubKeyValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PubKeyInfoType" /> class.</para>
        /// </summary>
        public PubKeyInfoType()
        {
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
    }
}
