//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("SignerInfoType", Namespace="urn:org:ebics:H004")]
    public partial class SignerInfoType
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 35.</para>
        /// <para xml:lang="en">Pattern: [a-zA-Z0-9,=]{1,35}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("PartnerID")]
        public string PartnerId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 35.</para>
        /// <para xml:lang="en">Pattern: [a-zA-Z0-9,=]{1,35}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("UserID")]
        public string UserId { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public string Name { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Timestamp", DataType="dateTime")]
        public System.DateTime Timestamp { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Permission")]
        public SignerInfoTypePermission Permission { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="SignerInfoType" /> class.</para>
        /// </summary>
        public SignerInfoType()
        {
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
    }
}
