//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H004
{
    
    
    /// <summary>
    /// <para xml:lang="en">Data type for order details stored in the static EBICS header.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("StaticHeaderOrderDetailsType", Namespace="urn:org:ebics:H004")]
    public partial class StaticHeaderOrderDetailsType
    {
        
        /// <summary>
        /// <para xml:lang="en">type code of the order.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderType")]
        public StaticHeaderOrderDetailsTypeOrderType OrderType { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">ID of the (upload) order, formatted in accordance with the document "DFÜ-Abkommen".</para>
        /// <para xml:lang="en">Minimum length: 4. Maximum length: 4.</para>
        /// <para xml:lang="en">Pattern: [A-Z][A-Z0-9]{3}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderID")]
        public string OrderId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">attribute describing the order contents.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderAttribute")]
        public EBICO.Core.Schema.H004.OrderAttributeType OrderAttribute { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("HVDOrderParams", Type=typeof(EBICO.Core.Schema.H004.HvdOrderParamsType), Namespace="urn:org:ebics:H004")]
        [System.Xml.Serialization.XmlElementAttribute("HVEOrderParams", Type=typeof(EBICO.Core.Schema.H004.HveOrderParamsType), Namespace="urn:org:ebics:H004")]
        [System.Xml.Serialization.XmlElementAttribute("HVSOrderParams", Type=typeof(EBICO.Core.Schema.H004.HvsOrderParamsType), Namespace="urn:org:ebics:H004")]
        [System.Xml.Serialization.XmlElementAttribute("HVTOrderParams", Type=typeof(EBICO.Core.Schema.H004.HvtOrderParamsType), Namespace="urn:org:ebics:H004")]
        [System.Xml.Serialization.XmlElementAttribute("HVUOrderParams", Type=typeof(EBICO.Core.Schema.H004.HvuOrderParamsType), Namespace="urn:org:ebics:H004")]
        [System.Xml.Serialization.XmlElementAttribute("HVZOrderParams", Type=typeof(EBICO.Core.Schema.H004.HvzOrderParamsType), Namespace="urn:org:ebics:H004")]
        [System.Xml.Serialization.XmlElementAttribute("FULOrderParams", Type=typeof(EBICO.Core.Schema.H004.FulOrderParamsType), Namespace="urn:org:ebics:H004")]
        [System.Xml.Serialization.XmlElementAttribute("FDLOrderParams", Type=typeof(EBICO.Core.Schema.H004.FdlOrderParamsType), Namespace="urn:org:ebics:H004")]
        [System.Xml.Serialization.XmlElementAttribute("StandardOrderParams", Type=typeof(EBICO.Core.Schema.H004.StandardOrderParamsType), Namespace="urn:org:ebics:H004")]
        [System.Xml.Serialization.XmlElementAttribute("GenericOrderParams", Type=typeof(EBICO.Core.Schema.H004.GenericOrderParamsType), Namespace="urn:org:ebics:H004")]
        [System.Xml.Serialization.XmlElementAttribute("OrderParams")]
        public object OrderParams { get; set; }
    }
}
