//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.XmlDsig
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("KeyValueType", Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("KeyValue", Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class KeyValueType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("DSAKeyValue")]
        public DsaKeyValueType DsaKeyValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("RSAKeyValue")]
        public RsaKeyValueType RsaKeyValue { get; set; }
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.Linq.XElement Any { get; set; }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text { get; set; }
    }
}
