//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.XmlDsig
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("SignedInfoType", Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("SignedInfo", Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignedInfoType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("CanonicalizationMethod")]
        public CanonicalizationMethodType CanonicalizationMethod { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("SignatureMethod")]
        public SignatureMethodType SignatureMethod { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ReferenceType> _reference;
        
        [System.Xml.Serialization.XmlElementAttribute("Reference")]
        public System.Collections.ObjectModel.Collection<ReferenceType> Reference
        {
            get
            {
                return _reference;
            }
            private set
            {
                _reference = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="SignedInfoType" /> class.</para>
        /// </summary>
        public SignedInfoType()
        {
            this._reference = new System.Collections.ObjectModel.Collection<ReferenceType>();
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Id")]
        public string Id { get; set; }
    }
}
