//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.XmlDsig
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("SignaturePropertiesType", Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("SignatureProperties", Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignaturePropertiesType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<SignaturePropertyType> _signatureProperty;
        
        [System.Xml.Serialization.XmlElementAttribute("SignatureProperty")]
        public System.Collections.ObjectModel.Collection<SignaturePropertyType> SignatureProperty
        {
            get
            {
                return _signatureProperty;
            }
            private set
            {
                _signatureProperty = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="SignaturePropertiesType" /> class.</para>
        /// </summary>
        public SignaturePropertiesType()
        {
            this._signatureProperty = new System.Collections.ObjectModel.Collection<SignaturePropertyType>();
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Id")]
        public string Id { get; set; }
    }
}
