//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.XmlDsig
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("X509IssuerSerialType", Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class X509IssuerSerialType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("X509IssuerName")]
        public string X509IssuerName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("X509SerialNumber")]
        public string X509SerialNumber { get; set; }
    }
}
