//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.Signature.S001
{
    
    
    /// <summary>
    /// <para xml:lang="en">Data type according for a digital signature (either autorising an order or applied for transportation), structured format.</para>
    /// <para xml:lang="en">Digital signature (either autorising an order or applied for transportation), structured format.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("OrderSignatureDataType", Namespace="http://www.ebics.org/S001")]
    [System.Xml.Serialization.XmlRootAttribute("OrderSignatureData", Namespace="http://www.ebics.org/S001")]
    public partial class OrderSignatureDataType
    {
        
        /// <summary>
        /// <para xml:lang="en">Version of the algorithm used for signature creation.</para>
        /// <para xml:lang="en">Minimum length: 4. Maximum length: 4.</para>
        /// <para xml:lang="en">Pattern: A\d{3}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("SignatureVersion")]
        public string SignatureVersion { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Digital signature.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("SignatureValue", DataType="base64Binary")]
        public byte[] SignatureValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Customer ID of the signer.</para>
        /// <para xml:lang="en">Maximum length: 35.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("PartnerID")]
        public string PartnerId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">User ID.</para>
        /// <para xml:lang="en">Maximum length: 35.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("UserID")]
        public string UserId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Parameter for X509Data</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("X509Data", Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public EBICO.Core.Schema.XmlDsig.X509DataType X509Data { get; set; }
    }
}
