//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.Signature.S001
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("UserSignatureDataSigBookTypeOrderSignature", Namespace="http://www.ebics.org/S001")]
    public partial class UserSignatureDataSigBookTypeOrderSignature
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Customer ID of the signer.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("PartnerID")]
        public string PartnerId { get; set; }
    }
}
