//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.Signature.S001
{
    
    
    /// <summary>
    /// <para xml:lang="en">Data type for digital signature data transferred using EBICS.</para>
    /// <para xml:lang="en">contains the digital signatures.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("UserSignatureDataSigBookType", Namespace="http://www.ebics.org/S001")]
    [System.Xml.Serialization.XmlRootAttribute("UserSignatureData", Namespace="http://www.ebics.org/S001")]
    public partial class UserSignatureDataSigBookType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<UserSignatureDataSigBookTypeOrderSignature> _orderSignature;
        
        /// <summary>
        /// <para xml:lang="en">Digital signature (either autorising an order or applied for transportation), binary format.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderSignature")]
        public System.Collections.ObjectModel.Collection<UserSignatureDataSigBookTypeOrderSignature> OrderSignature
        {
            get
            {
                return _orderSignature;
            }
            private set
            {
                _orderSignature = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the OrderSignature collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderSignatureSpecified
        {
            get
            {
                return (this.OrderSignature.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="UserSignatureDataSigBookType" /> class.</para>
        /// </summary>
        public UserSignatureDataSigBookType()
        {
            this._orderSignature = new System.Collections.ObjectModel.Collection<UserSignatureDataSigBookTypeOrderSignature>();
            this._orderSignatureData = new System.Collections.ObjectModel.Collection<OrderSignatureDataType>();
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<OrderSignatureDataType> _orderSignatureData;
        
        /// <summary>
        /// <para xml:lang="en">Digital signature (either autorising an order or applied for transportation), structured format.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderSignatureData")]
        public System.Collections.ObjectModel.Collection<OrderSignatureDataType> OrderSignatureData
        {
            get
            {
                return _orderSignatureData;
            }
            private set
            {
                _orderSignatureData = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the OrderSignatureData collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderSignatureDataSpecified
        {
            get
            {
                return (this.OrderSignatureData.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
    }
}
