//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.Hev
{
    
    
    /// <summary>
    /// <para xml:lang="en">Datentyp für die Response-Daten</para>
    /// <para xml:lang="en">Data type for Request data</para>
    /// <para xml:lang="en">response data</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("HEVResponseDataType", Namespace="http://www.ebics.org/H000")]
    [System.Xml.Serialization.XmlRootAttribute("ebicsHEVResponse", Namespace="http://www.ebics.org/H000")]
    public partial class HevResponseDataType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("SystemReturnCode")]
        public SystemReturnCodeType SystemReturnCode { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<HevResponseDataTypeVersionNumber> _versionNumber;
        
        /// <summary>
        /// <para xml:lang="en">EBICS-releases supported by the bank, e.g. 2.4</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("VersionNumber")]
        public System.Collections.ObjectModel.Collection<HevResponseDataTypeVersionNumber> VersionNumber
        {
            get
            {
                return _versionNumber;
            }
            private set
            {
                _versionNumber = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the VersionNumber collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VersionNumberSpecified
        {
            get
            {
                return (this.VersionNumber.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="HevResponseDataType" /> class.</para>
        /// </summary>
        public HevResponseDataType()
        {
            this._versionNumber = new System.Collections.ObjectModel.Collection<HevResponseDataTypeVersionNumber>();
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
    }
}
