//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.Hev
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("HevResponseDataTypeVersionNumber", Namespace="http://www.ebics.org/H000")]
    public partial class HevResponseDataTypeVersionNumber
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// <para xml:lang="en">Minimum length: 5. Maximum length: 5.</para>
        /// <para xml:lang="en">Pattern: [0-9]{2}[.][0-9]{2}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">EBICS-scheme-version, e.g. H003, well-defined for EBICS-release-Version</para>
        /// <para xml:lang="en">Datatype for release-number of the EBICS scheme</para>
        /// <para xml:lang="en">Minimum length: 4. Maximum length: 4.</para>
        /// <para xml:lang="en">Pattern: H\d{3}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("ProtocolVersion")]
        public string ProtocolVersion { get; set; }
    }
}
