//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.Hev
{
    
    
    /// <summary>
    /// <para xml:lang="en">Datatype for technical error</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("SystemReturnCodeType", Namespace="http://www.ebics.org/H000")]
    public partial class SystemReturnCodeType
    {
        
        /// <summary>
        /// <para xml:lang="en">Confirmation of the carried out status with a unique error code.</para>
        /// <para xml:lang="en">Datatype for the return code</para>
        /// <para xml:lang="en">Minimum length: 6. Maximum length: 6.</para>
        /// <para xml:lang="en">Pattern: \d{6}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ReturnCode")]
        public string ReturnCode { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Clear text of the response (carried out status).</para>
        /// <para xml:lang="en">Datatype for report text with respect to the return code</para>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ReportText")]
        public string ReportText { get; set; }
    }
}
