//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("AccountTypeAccountNumber", Namespace="urn:org:ebics:H005")]
    public partial class AccountTypeAccountNumber
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// <para xml:lang="en">Maximum length: 40.</para>
        /// <para xml:lang="en">Pattern: \d{3,10}|([A-Z]{2}\d{2}[A-Za-z0-9]{3,30}).</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _international = false;
        
        /// <summary>
        /// <para xml:lang="en">Is the account number specified using the national=German or the international=IBAN format?</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlAttributeAttribute("international")]
        public bool International
        {
            get
            {
                return _international;
            }
            set
            {
                _international = value;
            }
        }
    }
}
