//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("AuthenticationPubKeyInfoType", Namespace="urn:org:ebics:H005")]
    public partial class AuthenticationPubKeyInfoType : PubKeyInfoType
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 4. Maximum length: 4.</para>
        /// <para xml:lang="en">Pattern: X\d{3}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("AuthenticationVersion")]
        public string AuthenticationVersion { get; set; }
    }
}
