//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    /// <summary>
    /// <para>Datentyp für BTF Download Parameter</para>
    /// <para>zusätzliche Auftragsparameter für Auftragsart BTD.</para>
    /// <para xml:lang="en">additional order parameters for order type BTD.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("BTDParamsType", Namespace="urn:org:ebics:H005")]
    [System.Xml.Serialization.XmlRootAttribute("BTDOrderParams", Namespace="urn:org:ebics:H005")]
    public partial class BtdParamsType : BtfParamsTyp
    {
    }
}
