//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    /// <summary>
    /// <para>Abstract Type containing all BTF params structures</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("BTFParamsTyp", Namespace="urn:org:ebics:H005")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BtdParamsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BtuParamsType))]
    public abstract partial class BtfParamsTyp
    {
        
        /// <summary>
        /// <para>Service name - target system for the further processing of the order</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Service")]
        public RestrictedServiceType Service { get; set; }
        
        /// <summary>
        /// <para>If not present the order doesn't contain any ES and shall be authorised outside EBICS
        ///If present the order shall be autorised within EBICS: 
        ///1. If the attribute VEU is also present the sender desires spooling into the VEU - hence in this case the order is not rejected in the case of not sufficient number of ES
        ///2. If the attribute is not present all necessary ES must be inside the order (else: rejection of the order)</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("SignatureFlag")]
        public SignatureFlagType SignatureFlag { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("DateRange")]
        public DateRangeType DateRange { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<EBICO.Core.Schema.H005.Parameter> _parameter;
        
        [System.Xml.Serialization.XmlElementAttribute("Parameter")]
        public System.Collections.ObjectModel.Collection<EBICO.Core.Schema.H005.Parameter> Parameter
        {
            get
            {
                return _parameter;
            }
            private set
            {
                _parameter = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Parameter collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ParameterSpecified
        {
            get
            {
                return (this.Parameter.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="BtfParamsTyp" /> class.</para>
        /// </summary>
        public BtfParamsTyp()
        {
            this._parameter = new System.Collections.ObjectModel.Collection<EBICO.Core.Schema.H005.Parameter>();
        }
        
        /// <summary>
        /// <para>The file name on the client It can be transmitted optionally</para>
        /// <para>Type ist used for original file name</para>
        /// <para xml:lang="en">Minimum length: 1. Maximum length: 256.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("fileName")]
        public string FileName { get; set; }
    }
}
