//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    /// <summary>
    /// <para>Datentyp für BTF Upload Parameter</para>
    /// <para>zusätzliche Auftragsparameter für Auftragsart BTU.</para>
    /// <para xml:lang="en">additional order parameters for order type BTU.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("BTUParamsType", Namespace="urn:org:ebics:H005")]
    [System.Xml.Serialization.XmlRootAttribute("BTUOrderParams", Namespace="urn:org:ebics:H005")]
    public partial class BtuParamsType : BtfParamsTyp
    {
    }
}
