//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("ContainerStringType", Namespace="urn:org:ebics:H005")]
    public enum ContainerStringType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("SVC")]
        Svc,
        
        [System.Xml.Serialization.XmlEnumAttribute("XML")]
        Xml,
        
        [System.Xml.Serialization.XmlEnumAttribute("ZIP")]
        Zip,
    }
}
