//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    /// <summary>
    /// <para xml:lang="en">Data type for the modelling of information regarding the encryption of signature and order data.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("DataEncryptionInfoType", Namespace="urn:org:ebics:H005")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EBICO.Core.Schema.H005.DataTransferRequestTypeDataEncryptionInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EBICO.Core.Schema.H005.DataTransferResponseTypeDataEncryptionInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EBICO.Core.Schema.H005.EbicsKeyManagementResponseBodyDataTransferDataEncryptionInfo))]
    public partial class DataEncryptionInfoType
    {
        
        /// <summary>
        /// <para xml:lang="en">Hash value of the public encryption key owned by the receipient of the encrypted order data.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("EncryptionPubKeyDigest")]
        public DataEncryptionInfoTypeEncryptionPubKeyDigest EncryptionPubKeyDigest { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">The asymmetrically encrypted symmetric transaction key.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("TransactionKey", DataType="base64Binary")]
        public byte[] TransactionKey { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="DataEncryptionInfoType" /> class.</para>
        /// </summary>
        public DataEncryptionInfoType()
        {
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
    }
}
