//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    /// <summary>
    /// <para>Anfragestruktur für ungesicherte Auftragsarten HIA (Authentifikations- und Verschlüsselungsschlüssel senden) und INI (bankfachllichen Schlüssel senden).</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("ebicsUnsecuredRequest", Namespace="urn:org:ebics:H005", AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute("ebicsUnsecuredRequest", Namespace="urn:org:ebics:H005")]
    public partial class EbicsUnsecuredRequest : EBICO.Core.Schema.H005.IVersionAttrGroup
    {
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("header")]
        public EbicsUnsecuredRequestHeader Header { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("body")]
        public EbicsUnsecuredRequestBody Body { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Version of the EBICS protocol (e.g. "H00x").</para>
        /// <para xml:lang="en">Minimum length: 4. Maximum length: 4.</para>
        /// <para xml:lang="en">Pattern: H\d{3}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("Version")]
        public string Version { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Revision of the EBICS protocol (e.g. 1).</para>
        /// <para xml:lang="en">Maximum inclusive value: 99.</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlAttributeAttribute("Revision")]
        public byte RevisionValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Revision property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool RevisionValueSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Revision of the EBICS protocol (e.g. 1).</para>
        /// <para xml:lang="en">Maximum inclusive value: 99.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<byte> Revision
        {
            get
            {
                if (this.RevisionValueSpecified)
                {
                    return this.RevisionValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.RevisionValue = value.GetValueOrDefault();
                this.RevisionValueSpecified = value.HasValue;
            }
        }
    }
}
