//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("EbicsUnsignedRequestBodyDataTransfer", Namespace="urn:org:ebics:H005", AnonymousType=true)]
    public partial class EbicsUnsignedRequestBodyDataTransfer
    {
        
        /// <summary>
        /// <para xml:lang="en">Contains the ESs.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("SignatureData")]
        public EbicsUnsignedRequestBodyDataTransferSignatureData SignatureData { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Contains the order data</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderData")]
        public EbicsUnsignedRequestBodyDataTransferOrderData OrderData { get; set; }
    }
}
