//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("EbicsResponseBodyTimestampBankParameter", Namespace="urn:org:ebics:H005")]
    public partial class EbicsResponseBodyTimestampBankParameter : EBICO.Core.Schema.H005.IAuthenticationMarker
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute(DataType="dateTime")]
        public System.DateTime Value { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _authenticate = true;
        
        /// <summary>
        /// <para xml:lang="en">The element (and its substructures) that belongs to this attribute is to be authenticated.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("authenticate")]
        public bool Authenticate
        {
            get
            {
                return _authenticate;
            }
            set
            {
                _authenticate = value;
            }
        }
    }
}
