//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    /// <summary>
    /// <para xml:lang="en">Data type for order data of order type HAA (Response: Download of available order data).</para>
    /// <para xml:lang="en">Order data for order type HAA (response: receive downloadable order types).</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("HAAResponseOrderDataType", Namespace="urn:org:ebics:H005")]
    [System.Xml.Serialization.XmlRootAttribute("HAAResponseOrderData", Namespace="urn:org:ebics:H005")]
    public partial class HaaResponseOrderDataType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RestrictedServiceType> _service;
        
        /// <summary>
        /// <para xml:lang="en">List of order types for which data are available.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Service")]
        public System.Collections.ObjectModel.Collection<RestrictedServiceType> Service
        {
            get
            {
                return _service;
            }
            private set
            {
                _service = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Service collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ServiceSpecified
        {
            get
            {
                return (this.Service.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="HaaResponseOrderDataType" /> class.</para>
        /// </summary>
        public HaaResponseOrderDataType()
        {
            this._service = new System.Collections.ObjectModel.Collection<RestrictedServiceType>();
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
    }
}
