//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    /// <summary>
    /// <para xml:lang="en">Data type for order data for order type HVD (Response: EDS-status).</para>
    /// <para xml:lang="en">Order data for order type HVD (response: receive the status of an order currently stored in the distributed signature processing unit).</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("HVDResponseOrderDataType", Namespace="urn:org:ebics:H005")]
    [System.Xml.Serialization.XmlRootAttribute("HVDResponseOrderData", Namespace="urn:org:ebics:H005")]
    public partial class HvdResponseOrderDataType
    {
        
        /// <summary>
        /// <para xml:lang="en">Hash value of the order data.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("DataDigest")]
        public EBICO.Core.Schema.H005.DataDigestType DataDigest { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Accompanying ticket/"display file" (corresponds to the display file of the customer's journal according to the document "DFÜ-Abkommen").</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("DisplayFile", DataType="base64Binary")]
        public byte[] DisplayFile { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Can the order file be downloaded in the original format? (HVT with completeOrderData=true)</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderDataAvailable")]
        public bool OrderDataAvailable { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Size of the uncompressed order data (byte count).</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderDataSize")]
        public string OrderDataSize { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Can the order details be downloaded as XML document HVTResponseOrderData?  (HVT with completeOrderData=false)</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderDetailsAvailable")]
        public bool OrderDetailsAvailable { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<SignerInfoType> _signerInfo;
        
        /// <summary>
        /// <para xml:lang="en">Information about the already existing signers.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("SignerInfo")]
        public System.Collections.ObjectModel.Collection<SignerInfoType> SignerInfo
        {
            get
            {
                return _signerInfo;
            }
            private set
            {
                _signerInfo = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the SignerInfo collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SignerInfoSpecified
        {
            get
            {
                return (this.SignerInfo.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="HvdResponseOrderDataType" /> class.</para>
        /// </summary>
        public HvdResponseOrderDataType()
        {
            this._signerInfo = new System.Collections.ObjectModel.Collection<SignerInfoType>();
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
    }
}
