//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("HvtOrderInfoTypeDescriptionType", Namespace="urn:org:ebics:H005", AnonymousType=true)]
    public enum HvtOrderInfoTypeDescriptionType
    {
        
        /// <summary>
        /// <para xml:lang="en">remittance information.</para>
        /// </summary>
        Purpose,
        
        /// <summary>
        /// <para xml:lang="en">Order details.</para>
        /// </summary>
        Details,
        
        /// <summary>
        /// <para xml:lang="en">Annotation.</para>
        /// </summary>
        Comment,
    }
}
