//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("HvtOrderInfoTypeAmount", Namespace="urn:org:ebics:H005")]
    public partial class HvtOrderInfoTypeAmount
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// <para xml:lang="en">Total number of digits: 24.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 4.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Credit (isCredit = "true") or debit (isCredit = "false")?</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlAttributeAttribute("isCredit")]
        public bool IsCreditValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IsCredit property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool IsCreditValueSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Credit (isCredit = "true") or debit (isCredit = "false")?</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> IsCredit
        {
            get
            {
                if (this.IsCreditValueSpecified)
                {
                    return this.IsCreditValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IsCreditValue = value.GetValueOrDefault();
                this.IsCreditValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Currency code.</para>
        /// <para xml:lang="en">Minimum length: 3. Maximum length: 3.</para>
        /// <para xml:lang="en">Pattern: [A-Z]{3}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("Currency")]
        public string Currency { get; set; }
    }
}
