//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    /// <summary>
    /// <para xml:lang="en">Data type for HVU order details.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("HVUOrderDetailsType", Namespace="urn:org:ebics:H005")]
    public partial class HvuOrderDetailsType
    {
        
        /// <summary>
        /// <para xml:lang="en">Type of the order.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Service")]
        public RestrictedServiceType Service { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Order number.</para>
        /// <para xml:lang="en">Minimum length: 4. Maximum length: 4.</para>
        /// <para xml:lang="en">Pattern: [A-Z][A-Z0-9]{3}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderID")]
        public string OrderId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Order data size in bytes.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderDataSize")]
        public string OrderDataSize { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Signing information.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("SigningInfo")]
        public HvuSigningInfoType SigningInfo { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<SignerInfoType> _signerInfo;
        
        /// <summary>
        /// <para xml:lang="en">Information regarding the signer.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("SignerInfo")]
        public System.Collections.ObjectModel.Collection<SignerInfoType> SignerInfo
        {
            get
            {
                return _signerInfo;
            }
            private set
            {
                _signerInfo = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the SignerInfo collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SignerInfoSpecified
        {
            get
            {
                return (this.SignerInfo.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="HvuOrderDetailsType" /> class.</para>
        /// </summary>
        public HvuOrderDetailsType()
        {
            this._signerInfo = new System.Collections.ObjectModel.Collection<SignerInfoType>();
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
        
        /// <summary>
        /// <para xml:lang="en">Information regarding the originator.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OriginatorInfo")]
        public HvuOriginatorInfoType OriginatorInfo { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Additional Information about the order (unstructured, up to 255 characters).</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalOrderInfo")]
        public string AdditionalOrderInfo { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
    }
}
