//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("HVUSigningInfoType", Namespace="urn:org:ebics:H005")]
    public partial class HvuSigningInfoType
    {
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("readyToBeSigned")]
        public bool ReadyToBeSigned { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("NumSigRequired")]
        public string NumSigRequired { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("NumSigDone")]
        public string NumSigDone { get; set; }
    }
}
