//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("HvzPaymentOrderDetailsStructureFirstOrderInfoAccountInfoNationalAccountNumber", Namespace="urn:org:ebics:H005")]
    public partial class HvzPaymentOrderDetailsStructureFirstOrderInfoAccountInfoNationalAccountNumber
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// <para xml:lang="en">Maximum length: 40.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Format type.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("format")]
        public string Format { get; set; }
    }
}
