//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("HvzPaymentOrderDetailsStructureFirstOrderInfo", Namespace="urn:org:ebics:H005", AnonymousType=true)]
    public partial class HvzPaymentOrderDetailsStructureFirstOrderInfo
    {
        
        /// <summary>
        /// <para xml:lang="en">Order party information (from display file).</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderPartyInfo")]
        public string OrderPartyInfo { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">First order party account (from display file).</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("AccountInfo")]
        public HvzPaymentOrderDetailsStructureFirstOrderInfoAccountInfo AccountInfo { get; set; }
    }
}
