//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    /// <summary>
    /// <para xml:lang="en">Order data for order type HVZ (response: receive summary of orders currently stored in the distributed signature processing unit with additional informations).</para>
    /// <para xml:lang="en">Order data for order type HVZ (response: receive summary of orders currently stored in the distributed signature processing unit with additional information).</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("HVZResponseOrderDataType", Namespace="urn:org:ebics:H005")]
    [System.Xml.Serialization.XmlRootAttribute("HVZResponseOrderData", Namespace="urn:org:ebics:H005")]
    public partial class HvzResponseOrderDataType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<HvzOrderDetailsType> _orderDetails;
        
        /// <summary>
        /// <para xml:lang="en">Summary of order information.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderDetails")]
        public System.Collections.ObjectModel.Collection<HvzOrderDetailsType> OrderDetails
        {
            get
            {
                return _orderDetails;
            }
            private set
            {
                _orderDetails = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="HvzResponseOrderDataType" /> class.</para>
        /// </summary>
        public HvzResponseOrderDataType()
        {
            this._orderDetails = new System.Collections.ObjectModel.Collection<HvzOrderDetailsType>();
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
    }
}
