//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    /// <summary>
    /// <para xml:lang="en">Standard request structure for HVx orders (HVD, HVT, HVE, HVS).</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    public partial interface IHvRequestStructure
    {
        
        /// <summary>
        /// <para xml:lang="en">Customer ID of the presenter of the selected order.</para>
        /// <para xml:lang="en">Maximum length: 35.</para>
        /// <para xml:lang="en">Pattern: [a-zA-Z0-9,=]{1,35}.</para>
        /// </summary>
        string PartnerId
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para xml:lang="en">Identification of the file format in the case of FUL/FDL</para>
        /// </summary>
        RestrictedServiceType Service
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para xml:lang="en">Order ID of the selected order.</para>
        /// <para xml:lang="en">Minimum length: 4. Maximum length: 4.</para>
        /// <para xml:lang="en">Pattern: [A-Z][A-Z0-9]{3}.</para>
        /// </summary>
        string OrderId
        {
            get;
            set;
        }
    }
}
