//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    /// <summary>
    /// <para xml:lang="en">permission information of a user's digital signature.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    public partial interface ISignerPermission
    {
        
        /// <summary>
        /// <para xml:lang="en">Authorisation level of the user that signed the order.</para>
        /// </summary>
        EBICO.Core.Schema.H005.AuthorisationLevelType AuthorisationLevel
        {
            get;
            set;
        }
    }
}
