//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("KeyMgmntResponseMutableHeaderType", Namespace="urn:org:ebics:H005")]
    public partial class KeyMgmntResponseMutableHeaderType
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 4. Maximum length: 4.</para>
        /// <para xml:lang="en">Pattern: [A-Z][A-Z0-9]{3}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderID")]
        public string OrderId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 6. Maximum length: 6.</para>
        /// <para xml:lang="en">Pattern: \d{6}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ReturnCode")]
        public string ReturnCode { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ReportText")]
        public string ReportText { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="KeyMgmntResponseMutableHeaderType" /> class.</para>
        /// </summary>
        public KeyMgmntResponseMutableHeaderType()
        {
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
    }
}
