//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    /// <summary>
    /// <para>Datentyp für Meldungstyp-String mit optionalen Attributen</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("MessageType", Namespace="urn:org:ebics:H005")]
    public partial class MessageType
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// <para xml:lang="en">Minimum length: 1. Maximum length: 10.</para>
        /// <para xml:lang="en">Pattern: [a-z\.0-9]*.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        /// <summary>
        /// <para>Variant number of the message type (usable for ISO20022 messages)</para>
        /// <para>Type is used for ISO variant and version</para>
        /// <para xml:lang="en">Minimum length: 2. Maximum length: 3.</para>
        /// <para xml:lang="en">Pattern: [0-9]*.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("variant")]
        public string Variant { get; set; }
        
        /// <summary>
        /// <para>Version number of the message type  (usable for ISO20022 messages)</para>
        /// <para>Type is used for ISO variant and version</para>
        /// <para xml:lang="en">Minimum length: 2. Maximum length: 3.</para>
        /// <para xml:lang="en">Pattern: [0-9]*.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("version")]
        public string Version { get; set; }
        
        /// <summary>
        /// <para>Encoding format of the message (e.g. XML, ASN1, JSON, PDF)</para>
        /// <para xml:lang="en">Minimum length: 1. Maximum length: 4.</para>
        /// <para xml:lang="en">Pattern: [A-Z0-9]*.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("format")]
        public string Format { get; set; }
    }
}
