//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("OrderDetailsType", Namespace="urn:org:ebics:H005")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NoPubKeyDigestsReqOrderDetailsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnsecuredReqOrderDetailsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnsignedReqOrderDetailsType))]
    // EBICO fixup (issue #117, ADR-0029) - applied by scripts/generate-bindings.sh:
    // the generated type is `abstract`, which makes the XmlSerializer demand an
    // xsi:type discriminator on <OrderDetails>. Real third-party clients follow the
    // concrete schema type and omit it. The [XmlInclude]s above stay, so a request
    // that does carry the discriminator still deserializes.
    public partial class OrderDetailsType
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 3. Maximum length: 3.</para>
        /// <para xml:lang="en">Pattern: [A-Z0-9]{3}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("AdminOrderType")]
        public string AdminOrderType { get; set; }
    }
}
