//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    /// <summary>
    /// <para xml:lang="en">Data type for the account authorisation data for the prevalidation.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("PreValidationAccountAuthType", Namespace="urn:org:ebics:H005")]
    public partial class PreValidationAccountAuthType : EBICO.Core.Schema.H005.AccountType
    {
        
        /// <summary>
        /// <para xml:lang="en">Total sum of the ordered payments regarding this account in order to check the maximum amount limit of the signature permission grades.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Amount")]
        public EBICO.Core.Schema.H005.AmountType Amount { get; set; }
    }
}
