//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    /// <summary>
    /// <para>Basisdatentyp für BTF-Service Parameter Set</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("ServiceType", Namespace="urn:org:ebics:H005")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RestrictedServiceType))]
    public partial class ServiceType
    {
        
        /// <summary>
        /// <para>Service Code name: External list specified and maintained by EBICS. Basis is the "SWIFT-list" for the field "description" (SCT, DCT, XCT, SDD, DDD, STM, REP...) plus additional codes needed for further services</para>
        /// <para>Service Code name: External list specified and maintained by EBICS. Basis is the "SWIFT-list" for the field "description" (SCT, DCT, XCT, SDD, DDD, STM, REP...) plus additional codes needed for further services</para>
        /// <para xml:lang="en">Minimum length: 3. Maximum length: 3.</para>
        /// <para xml:lang="en">Pattern: [A-Z0-9]*.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ServiceName")]
        public string ServiceName { get; set; }
        
        /// <summary>
        /// <para>Specifies whose rules have to be taken into account for the service. This means which market / comminity has defined the rules. 
        ///If the element is absent a global definition for the service is assumed.
        ///External list specified and maintained by EBICS. In addition the following codes may be used:
        ///2-character ISO country code or a 3-character issuer code (defined by EBICS)</para>
        /// <para xml:lang="en">Minimum length: 2. Maximum length: 3.</para>
        /// <para xml:lang="en">Pattern: [A-Z0-9]*.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Scope")]
        public string Scope { get; set; }
        
        /// <summary>
        /// <para>Service Option Code
        ///Additional option for the service (also depends on used scope)</para>
        /// <para xml:lang="en">Minimum length: 3. Maximum length: 10.</para>
        /// <para xml:lang="en">Pattern: [A-Z0-9]*.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ServiceOption")]
        public string ServiceOption { get; set; }
        
        /// <summary>
        /// <para>Container flag. If present, data is provided/requested in a container format specified in the attribute of the flag</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Container")]
        public ContainerFlagType Container { get; set; }
        
        /// <summary>
        /// <para>Name of the message, e.g. pain.001 or mt101 National message names (issued by DK, CFONB or SIC are also allowed)</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("MsgName")]
        public MessageType MsgName { get; set; }
    }
}
