//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    /// <summary>
    /// <para xml:lang="en">Data type for public authorisation (ES) key.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("SignatureCertificateInfoType", Namespace="urn:org:ebics:H005")]
    public partial class SignatureCertificateInfoType : CertificateInfoType
    {
        
        /// <summary>
        /// <para xml:lang="en">ES-Version.</para>
        /// <para xml:lang="en">Minimum length: 4. Maximum length: 4.</para>
        /// <para xml:lang="en">Pattern: A\d{3}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("SignatureVersion")]
        public string SignatureVersion { get; set; }
    }
}
