//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("StaticHeaderTypeProduct", Namespace="urn:org:ebics:H005")]
    public partial class StaticHeaderTypeProduct
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// <para xml:lang="en">Maximum length: 64.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Language code of the customer's software package according to ISO 639.</para>
        /// <para xml:lang="en">Minimum length: 2. Maximum length: 2.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("Language")]
        public string Language { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">ID of the manufacturer / financial institute providing support for the customer's software package.</para>
        /// <para xml:lang="en">Maximum length: 64.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("InstituteID")]
        public string InstituteId { get; set; }
    }
}
