//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    /// <summary>
    /// <para xml:lang="en">Data type for the static EBICS header.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("StaticHeaderType", Namespace="urn:org:ebics:H005")]
    public partial class StaticHeaderType
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 35.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("HostID")]
        public string HostId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Random value, ensures the uniqueness of the client's message during initialisation phase.</para>
        /// <para xml:lang="en">Minimum length: 16. Maximum length: 16.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Nonce", DataType="hexBinary")]
        public byte[] Nonce { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">current timestamp, used to limit storage space for nonces on the server.</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("Timestamp", DataType="dateTime")]
        public System.DateTime TimestampValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Timestamp property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TimestampValueSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">current timestamp, used to limit storage space for nonces on the server.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> Timestamp
        {
            get
            {
                if (this.TimestampValueSpecified)
                {
                    return this.TimestampValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TimestampValue = value.GetValueOrDefault();
                this.TimestampValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">ID of the partner = customer, administered on the server.</para>
        /// <para xml:lang="en">Maximum length: 35.</para>
        /// <para xml:lang="en">Pattern: [a-zA-Z0-9,=]{1,35}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("PartnerID")]
        public string PartnerId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">ID of the user that is assigned to the given customer, administered on the server.</para>
        /// <para xml:lang="en">Maximum length: 35.</para>
        /// <para xml:lang="en">Pattern: [a-zA-Z0-9,=]{1,35}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("UserID")]
        public string UserId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">ID of the system for multi-user systems.</para>
        /// <para xml:lang="en">Maximum length: 35.</para>
        /// <para xml:lang="en">Pattern: [a-zA-Z0-9,=]{1,35}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("SystemID")]
        public string SystemId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">software ID / manufacturer ID / manufacturer's name of the customer's software package.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Product", IsNullable=true)]
        public StaticHeaderTypeProduct Product { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">order details.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderDetails")]
        public StaticHeaderOrderDetailsType OrderDetails { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Digest values of the expected public keys (authentication, encryption, signature) owned by the financial institute.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("BankPubKeyDigests")]
        public StaticHeaderTypeBankPubKeyDigests BankPubKeyDigests { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Classification of the security medium used by the customer.</para>
        /// <para xml:lang="en">Minimum length: 4. Maximum length: 4.</para>
        /// <para xml:lang="en">Pattern: \d{4}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("SecurityMedium")]
        public string SecurityMedium { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Total number of segments for this transaction; mandatory for uploads only.</para>
        /// <para xml:lang="en">Total number of digits: 10.</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("NumSegments")]
        public ulong NumSegmentsValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the NumSegments property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool NumSegmentsValueSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Total number of segments for this transaction; mandatory for uploads only.</para>
        /// <para xml:lang="en">Total number of digits: 10.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<ulong> NumSegments
        {
            get
            {
                if (this.NumSegmentsValueSpecified)
                {
                    return this.NumSegmentsValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.NumSegmentsValue = value.GetValueOrDefault();
                this.NumSegmentsValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="StaticHeaderType" /> class.</para>
        /// </summary>
        public StaticHeaderType()
        {
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
        
        /// <summary>
        /// <para xml:lang="en">unique transaction ID, provided by the server.</para>
        /// <para xml:lang="en">Minimum length: 16. Maximum length: 16.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("TransactionID", DataType="hexBinary")]
        public byte[] TransactionId { get; set; }
    }
}
