//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    /// <summary>
    /// <para xml:lang="en">Data type for order details stored in the static EBICS header.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("StaticHeaderOrderDetailsType", Namespace="urn:org:ebics:H005")]
    public partial class StaticHeaderOrderDetailsType
    {
        
        /// <summary>
        /// <para xml:lang="en">type code of the order.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("AdminOrderType")]
        public StaticHeaderOrderDetailsTypeAdminOrderType AdminOrderType { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">ID of the (upload) order, formatted in accordance with the document "DFÜ-Abkommen".</para>
        /// <para xml:lang="en">Minimum length: 4. Maximum length: 4.</para>
        /// <para xml:lang="en">Pattern: [A-Z][A-Z0-9]{3}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderID")]
        public string OrderId { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("HVDOrderParams", Type=typeof(EBICO.Core.Schema.H005.HvdOrderParamsType), Namespace="urn:org:ebics:H005")]
        [System.Xml.Serialization.XmlElementAttribute("HVEOrderParams", Type=typeof(EBICO.Core.Schema.H005.HveOrderParamsType), Namespace="urn:org:ebics:H005")]
        [System.Xml.Serialization.XmlElementAttribute("HVSOrderParams", Type=typeof(EBICO.Core.Schema.H005.HvsOrderParamsType), Namespace="urn:org:ebics:H005")]
        [System.Xml.Serialization.XmlElementAttribute("HVTOrderParams", Type=typeof(EBICO.Core.Schema.H005.HvtOrderParamsType), Namespace="urn:org:ebics:H005")]
        [System.Xml.Serialization.XmlElementAttribute("HVUOrderParams", Type=typeof(EBICO.Core.Schema.H005.HvuOrderParamsType), Namespace="urn:org:ebics:H005")]
        [System.Xml.Serialization.XmlElementAttribute("HVZOrderParams", Type=typeof(EBICO.Core.Schema.H005.HvzOrderParamsType), Namespace="urn:org:ebics:H005")]
        [System.Xml.Serialization.XmlElementAttribute("StandardOrderParams", Type=typeof(EBICO.Core.Schema.H005.StandardOrderParamsType), Namespace="urn:org:ebics:H005")]
        [System.Xml.Serialization.XmlElementAttribute("BTDOrderParams", Type=typeof(EBICO.Core.Schema.H005.BtdParamsType), Namespace="urn:org:ebics:H005")]
        [System.Xml.Serialization.XmlElementAttribute("BTUOrderParams", Type=typeof(EBICO.Core.Schema.H005.BtuParamsType), Namespace="urn:org:ebics:H005")]
        [System.Xml.Serialization.XmlElementAttribute("OrderParams")]
        public object OrderParams { get; set; }
    }
}
