//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("StaticHeaderTypeBankPubKeyDigests", Namespace="urn:org:ebics:H005", AnonymousType=true)]
    public partial class StaticHeaderTypeBankPubKeyDigests
    {
        
        /// <summary>
        /// <para xml:lang="en">Digest value of the public authentication key.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Authentication")]
        public StaticHeaderTypeBankPubKeyDigestsAuthentication Authentication { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Digest value of the public encryption key.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Encryption")]
        public StaticHeaderTypeBankPubKeyDigestsEncryption Encryption { get; set; }
    }
}
