//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H005
{
    
    
    /// <summary>
    /// <para>Datentyp zur Kennzeichnung von Auftragsartenbeschränkungen</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("UsageOrderType", Namespace="urn:org:ebics:H005")]
    public partial class UsageOrderType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RestrictedServiceType> _service;
        
        /// <summary>
        /// <para>Service Parameter-Sets von nicht unterstützten BTF-Auftragsarten</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Service")]
        public System.Collections.ObjectModel.Collection<RestrictedServiceType> Service
        {
            get
            {
                return _service;
            }
            private set
            {
                _service = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Service collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ServiceSpecified
        {
            get
            {
                return (this.Service.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="UsageOrderType" /> class.</para>
        /// </summary>
        public UsageOrderType()
        {
            this._service = new System.Collections.ObjectModel.Collection<RestrictedServiceType>();
        }
    }
}
