//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H003
{
    
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("AccountNumberRoleType", Namespace="http://www.ebics.org/H003")]
    public enum AccountNumberRoleType
    {
        
        /// <summary>
        /// </summary>
        Originator,
        
        /// <summary>
        /// </summary>
        Recipient,
        
        /// <summary>
        /// </summary>
        Charges,
        
        /// <summary>
        /// </summary>
        Other,
    }
}
