//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H003
{
    
    
    /// <summary>
    /// <para>Anfragestruktur für Sendeaufträge mit EU-Datei und Nutzdaten aber ohne Authentifizierungssignatur und Digests der Bankschlüssel (Auftrag HSA Authentifikations- und Verschlüsselungsschlüssel senden, signiert mit FTAM-Schlüssel).</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("ebicsUnsignedRequest", Namespace="http://www.ebics.org/H003", AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute("ebicsUnsignedRequest", Namespace="http://www.ebics.org/H003")]
    public partial class EbicsUnsignedRequest : EBICO.Core.Schema.H003.IVersionAttrGroup
    {
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("header")]
        public EbicsUnsignedRequestHeader Header { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("body")]
        public EbicsUnsignedRequestBody Body { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Version of the EBICS protocol (e.g. "H003").</para>
        /// <para xml:lang="en">Minimum length: 4. Maximum length: 4.</para>
        /// <para xml:lang="en">Pattern: H\d{3}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("Version")]
        public string Version { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Revision of the EBICS protocol (e.g. 1).</para>
        /// <para xml:lang="en">Maximum inclusive value: 99.</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlAttributeAttribute("Revision")]
        public byte RevisionValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Revision property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool RevisionValueSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Revision of the EBICS protocol (e.g. 1).</para>
        /// <para xml:lang="en">Maximum inclusive value: 99.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<byte> Revision
        {
            get
            {
                if (this.RevisionValueSpecified)
                {
                    return this.RevisionValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.RevisionValue = value.GetValueOrDefault();
                this.RevisionValueSpecified = value.HasValue;
            }
        }
    }
}
