//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H003
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("EbicsResponseBodyReturnCode", Namespace="http://www.ebics.org/H003")]
    public partial class EbicsResponseBodyReturnCode : EBICO.Core.Schema.H003.IAuthenticationMarker
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// <para xml:lang="en">Minimum length: 6. Maximum length: 6.</para>
        /// <para xml:lang="en">Pattern: \d{6}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _authenticate = true;
        
        /// <summary>
        /// <para xml:lang="en">The element (and its substructures) that belongs to this attribute is to be authenticated.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("authenticate")]
        public bool Authenticate
        {
            get
            {
                return _authenticate;
            }
            set
            {
                _authenticate = value;
            }
        }
    }
}
