//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H003
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("EbicsKeyManagementResponseHeader", Namespace="http://www.ebics.org/H003", AnonymousType=true)]
    public partial class EbicsKeyManagementResponseHeader : EBICO.Core.Schema.H003.IAuthenticationMarker
    {
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("static")]
        public EbicsKeyManagementResponseHeaderStatic Static { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("mutable")]
        public KeyMgmntResponseMutableHeaderType Mutable { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _authenticate = true;
        
        /// <summary>
        /// <para xml:lang="en">The element (and its substructures) that belongs to this attribute is to be authenticated.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("authenticate")]
        public bool Authenticate
        {
            get
            {
                return _authenticate;
            }
            set
            {
                _authenticate = value;
            }
        }
    }
}
