//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H003
{
    
    
    /// <summary>
    /// <para xml:lang="en">additional order parameters for order type FDL.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("FDLOrderParamsType", Namespace="http://www.ebics.org/H003")]
    [System.Xml.Serialization.XmlRootAttribute("FDLOrderParams", Namespace="http://www.ebics.org/H003")]
    public partial class FdlOrderParamsType
    {
        
        /// <summary>
        /// <para xml:lang="en">Range of date (from-to).</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("DateRange")]
        public FdlOrderParamsTypeDateRange DateRange { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<EBICO.Core.Schema.H003.Parameter> _parameter;
        
        [System.Xml.Serialization.XmlElementAttribute("Parameter")]
        public System.Collections.ObjectModel.Collection<EBICO.Core.Schema.H003.Parameter> Parameter
        {
            get
            {
                return _parameter;
            }
            private set
            {
                _parameter = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Parameter collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ParameterSpecified
        {
            get
            {
                return (this.Parameter.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="FdlOrderParamsType" /> class.</para>
        /// </summary>
        public FdlOrderParamsType()
        {
            this._parameter = new System.Collections.ObjectModel.Collection<EBICO.Core.Schema.H003.Parameter>();
        }
        
        /// <summary>
        /// <para xml:lang="en">Name of data format</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("FileFormat")]
        public EBICO.Core.Schema.H003.FileFormatType FileFormat { get; set; }
    }
}
