//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H003
{
    
    
    /// <summary>
    /// <para xml:lang="en">Order data for order type HCS (request: replace all keys).</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("HCSRequestOrderDataType", Namespace="http://www.ebics.org/H003")]
    [System.Xml.Serialization.XmlRootAttribute("HCSRequestOrderData", Namespace="http://www.ebics.org/H003")]
    public partial class HcsRequestOrderDataType
    {
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("AuthenticationPubKeyInfo")]
        public EBICO.Core.Schema.H003.AuthenticationPubKeyInfoType AuthenticationPubKeyInfo { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("EncryptionPubKeyInfo")]
        public EBICO.Core.Schema.H003.EncryptionPubKeyInfoType EncryptionPubKeyInfo { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("SignaturePubKeyInfo", Namespace="http://www.ebics.org/S001")]
        public EBICO.Core.Schema.Signature.S001.SignaturePubKeyInfoType SignaturePubKeyInfo { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 35.</para>
        /// <para xml:lang="en">Pattern: [a-zA-Z0-9,=]{1,35}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("PartnerID")]
        public string PartnerId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 35.</para>
        /// <para xml:lang="en">Pattern: [a-zA-Z0-9,=]{1,35}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("UserID")]
        public string UserId { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="HcsRequestOrderDataType" /> class.</para>
        /// </summary>
        public HcsRequestOrderDataType()
        {
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
    }
}
