//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H003
{
    
    
    /// <summary>
    /// <para xml:lang="en">Order data for order type HKD (response: receive customer based information on the customer and the customer's user.</para>
    /// <para xml:lang="en">Order data for order type HKD (response: receive customer-based information on the customer and the customer's users).</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("HKDResponseOrderDataType", Namespace="http://www.ebics.org/H003")]
    [System.Xml.Serialization.XmlRootAttribute("HKDResponseOrderData", Namespace="http://www.ebics.org/H003")]
    public partial class HkdResponseOrderDataType
    {
        
        /// <summary>
        /// <para xml:lang="en">Customer data.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("PartnerInfo")]
        public PartnerInfoType PartnerInfo { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<UserInfoType> _userInfo;
        
        /// <summary>
        /// <para xml:lang="en">User data.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("UserInfo")]
        public System.Collections.ObjectModel.Collection<UserInfoType> UserInfo
        {
            get
            {
                return _userInfo;
            }
            private set
            {
                _userInfo = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="HkdResponseOrderDataType" /> class.</para>
        /// </summary>
        public HkdResponseOrderDataType()
        {
            this._userInfo = new System.Collections.ObjectModel.Collection<UserInfoType>();
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
    }
}
