//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H003
{
    
    
    /// <summary>
    /// <para xml:lang="en">Order data for order type HPD (response: receive bank parameters).</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("HPDResponseOrderDataType", Namespace="http://www.ebics.org/H003")]
    [System.Xml.Serialization.XmlRootAttribute("HPDResponseOrderData", Namespace="http://www.ebics.org/H003")]
    public partial class HpdResponseOrderDataType
    {
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("AccessParams")]
        public HpdAccessParamsType AccessParams { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ProtocolParams")]
        public HpdProtocolParamsType ProtocolParams { get; set; }
    }
}
