//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H003
{
    
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("HPDVersionType", Namespace="http://www.ebics.org/H003")]
    public partial class HpdVersionType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _protocol;
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Protocol")]
        public System.Collections.ObjectModel.Collection<string> Protocol
        {
            get
            {
                return _protocol;
            }
            private set
            {
                _protocol = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="HpdVersionType" /> class.</para>
        /// </summary>
        public HpdVersionType()
        {
            this._protocol = new System.Collections.ObjectModel.Collection<string>();
            this._authentication = new System.Collections.ObjectModel.Collection<string>();
            this._encryption = new System.Collections.ObjectModel.Collection<string>();
            this._signature = new System.Collections.ObjectModel.Collection<string>();
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _authentication;
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Authentication")]
        public System.Collections.ObjectModel.Collection<string> Authentication
        {
            get
            {
                return _authentication;
            }
            private set
            {
                _authentication = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _encryption;
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Encryption")]
        public System.Collections.ObjectModel.Collection<string> Encryption
        {
            get
            {
                return _encryption;
            }
            private set
            {
                _encryption = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _signature;
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Signature")]
        public System.Collections.ObjectModel.Collection<string> Signature
        {
            get
            {
                return _signature;
            }
            private set
            {
                _signature = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
    }
}
