//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H003
{
    
    
    /// <summary>
    /// <para xml:lang="en">additional order parameters for order type HVS.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("HVSOrderParamsType", Namespace="http://www.ebics.org/H003")]
    [System.Xml.Serialization.XmlRootAttribute("HVSOrderParams", Namespace="http://www.ebics.org/H003")]
    public partial class HvsOrderParamsType : IHvRequestStructure
    {
        
        /// <summary>
        /// <para xml:lang="en">Customer ID of the presenter of the selected order.</para>
        /// <para xml:lang="en">Maximum length: 35.</para>
        /// <para xml:lang="en">Pattern: [a-zA-Z0-9,=]{1,35}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("PartnerID")]
        public string PartnerId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Order type of the selected order.</para>
        /// <para xml:lang="en">Minimum length: 3. Maximum length: 3.</para>
        /// <para xml:lang="en">Pattern: [A-Z0-9]{3}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderType")]
        public string OrderType { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Order ID of the selected order.</para>
        /// <para xml:lang="en">Minimum length: 4. Maximum length: 4.</para>
        /// <para xml:lang="en">Pattern: [A-Z][A-Z0-9]{3}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderID")]
        public string OrderId { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="HvsOrderParamsType" /> class.</para>
        /// </summary>
        public HvsOrderParamsType()
        {
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
    }
}
