//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H003
{
    
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("HVTOrderFlagsType", Namespace="http://www.ebics.org/H003")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HvtOrderParamsTypeOrderFlags))]
    public partial class HvtOrderFlagsType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _completeOrderData = false;
        
        /// <summary>
        /// <para xml:lang="en">Are the transaction details so be transmitted as particular order content information requested for display matters or in complete order data file form?</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlAttributeAttribute("completeOrderData")]
        public bool CompleteOrderData
        {
            get
            {
                return _completeOrderData;
            }
            set
            {
                _completeOrderData = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private ulong _fetchLimit = 100ul;
        
        /// <summary>
        /// <para xml:lang="en">Limit for the transaction details to be transmitted; if completeOrderData=false, maximum number of details of a particular order; 0 for unlimited number of details.</para>
        /// <para xml:lang="en">Total number of digits: 10.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(100ul)]
        [System.Xml.Serialization.XmlAttributeAttribute("fetchLimit")]
        public ulong FetchLimit
        {
            get
            {
                return _fetchLimit;
            }
            set
            {
                _fetchLimit = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private ulong _fetchOffset = 0ul;
        
        /// <summary>
        /// <para xml:lang="en">Offset position in the original order file which marks the starting point for the transaction details to be transmitted; applies to the sequential number of a particular order if completeOrderData=false.</para>
        /// <para xml:lang="en">Total number of digits: 10.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(0ul)]
        [System.Xml.Serialization.XmlAttributeAttribute("fetchOffset")]
        public ulong FetchOffset
        {
            get
            {
                return _fetchOffset;
            }
            set
            {
                _fetchOffset = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.XmlAttribute> _anyAttribute;
        
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="HvtOrderFlagsType" /> class.</para>
        /// </summary>
        public HvtOrderFlagsType()
        {
            this._anyAttribute = new System.Collections.ObjectModel.Collection<System.Xml.XmlAttribute>();
        }
    }
}
