//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H003
{
    
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("HVTOrderInfoType", Namespace="http://www.ebics.org/H003")]
    public partial class HvtOrderInfoType
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 8.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderFormat")]
        public string OrderFormat { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<HvtAccountInfoType> _accountInfo;
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("AccountInfo")]
        public System.Collections.ObjectModel.Collection<HvtAccountInfoType> AccountInfo
        {
            get
            {
                return _accountInfo;
            }
            private set
            {
                _accountInfo = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="HvtOrderInfoType" /> class.</para>
        /// </summary>
        public HvtOrderInfoType()
        {
            this._accountInfo = new System.Collections.ObjectModel.Collection<HvtAccountInfoType>();
            this._description = new System.Collections.ObjectModel.Collection<HvtOrderInfoTypeDescription>();
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ExecutionDate")]
        public HvtOrderInfoTypeExecutionDate ExecutionDate { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Amount")]
        public HvtOrderInfoTypeAmount Amount { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<HvtOrderInfoTypeDescription> _description;
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public System.Collections.ObjectModel.Collection<HvtOrderInfoTypeDescription> Description
        {
            get
            {
                return _description;
            }
            private set
            {
                _description = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Description collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DescriptionSpecified
        {
            get
            {
                return (this.Description.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
    }
}
