//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H003
{
    
    
    /// <summary>
    /// <para xml:lang="en">Data type for additional order parameters for order type HVT.</para>
    /// <para xml:lang="en">additional order parameters for order type HVT.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("HVTOrderParamsType", Namespace="http://www.ebics.org/H003")]
    [System.Xml.Serialization.XmlRootAttribute("HVTOrderParams", Namespace="http://www.ebics.org/H003")]
    public partial class HvtOrderParamsType : IHvRequestStructure
    {
        
        /// <summary>
        /// <para xml:lang="en">Customer ID of the presenter of the selected order.</para>
        /// <para xml:lang="en">Maximum length: 35.</para>
        /// <para xml:lang="en">Pattern: [a-zA-Z0-9,=]{1,35}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("PartnerID")]
        public string PartnerId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Order type of the selected order.</para>
        /// <para xml:lang="en">Minimum length: 3. Maximum length: 3.</para>
        /// <para xml:lang="en">Pattern: [A-Z0-9]{3}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderType")]
        public string OrderType { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Order ID of the selected order.</para>
        /// <para xml:lang="en">Minimum length: 4. Maximum length: 4.</para>
        /// <para xml:lang="en">Pattern: [A-Z][A-Z0-9]{3}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderID")]
        public string OrderId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Special order flags for orders of type HVT.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderFlags")]
        public HvtOrderParamsTypeOrderFlags OrderFlags { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<EBICO.Core.Schema.H003.Parameter> _parameter;
        
        /// <summary>
        /// <para xml:lang="en">Generic key-value parameters</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Parameter")]
        public System.Collections.ObjectModel.Collection<EBICO.Core.Schema.H003.Parameter> Parameter
        {
            get
            {
                return _parameter;
            }
            private set
            {
                _parameter = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Parameter collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ParameterSpecified
        {
            get
            {
                return (this.Parameter.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="HvtOrderParamsType" /> class.</para>
        /// </summary>
        public HvtOrderParamsType()
        {
            this._parameter = new System.Collections.ObjectModel.Collection<EBICO.Core.Schema.H003.Parameter>();
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
    }
}
