//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H003
{
    
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("HVTResponseOrderDataType", Namespace="http://www.ebics.org/H003")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HvtResponseOrderData))]
    public partial class HvtResponseOrderDataType
    {
        
        /// <summary>
        /// <para xml:lang="en">Total number of order infos for the order.</para>
        /// <para xml:lang="en">Total number of digits: 10.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("NumOrderInfos")]
        public ulong NumOrderInfos { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<HvtOrderInfoType> _orderInfo;
        
        /// <summary>
        /// <para xml:lang="en">Particular order content information requested for display matters.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderInfo")]
        public System.Collections.ObjectModel.Collection<HvtOrderInfoType> OrderInfo
        {
            get
            {
                return _orderInfo;
            }
            private set
            {
                _orderInfo = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="HvtResponseOrderDataType" /> class.</para>
        /// </summary>
        public HvtResponseOrderDataType()
        {
            this._orderInfo = new System.Collections.ObjectModel.Collection<HvtOrderInfoType>();
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
    }
}
