//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H003
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("HvzPaymentOrderDetailsStructureFirstOrderInfoAccountInfo", Namespace="http://www.ebics.org/H003", AnonymousType=true)]
    public partial class HvzPaymentOrderDetailsStructureFirstOrderInfoAccountInfo
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<HvzPaymentOrderDetailsStructureFirstOrderInfoAccountInfoAccountNumber> _accountNumber;
        
        /// <summary>
        /// <para xml:lang="en">Account number (German format or international as IBAN).</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("AccountNumber")]
        public System.Collections.ObjectModel.Collection<HvzPaymentOrderDetailsStructureFirstOrderInfoAccountInfoAccountNumber> AccountNumber
        {
            get
            {
                return _accountNumber;
            }
            private set
            {
                _accountNumber = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AccountNumber collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccountNumberSpecified
        {
            get
            {
                return (this.AccountNumber.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="HvzPaymentOrderDetailsStructureFirstOrderInfoAccountInfo" /> class.</para>
        /// </summary>
        public HvzPaymentOrderDetailsStructureFirstOrderInfoAccountInfo()
        {
            this._accountNumber = new System.Collections.ObjectModel.Collection<HvzPaymentOrderDetailsStructureFirstOrderInfoAccountInfoAccountNumber>();
            this._nationalAccountNumber = new System.Collections.ObjectModel.Collection<HvzPaymentOrderDetailsStructureFirstOrderInfoAccountInfoNationalAccountNumber>();
            this._bankCode = new System.Collections.ObjectModel.Collection<HvzPaymentOrderDetailsStructureFirstOrderInfoAccountInfoBankCode>();
            this._nationalBankCode = new System.Collections.ObjectModel.Collection<HvzPaymentOrderDetailsStructureFirstOrderInfoAccountInfoNationalBankCode>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<HvzPaymentOrderDetailsStructureFirstOrderInfoAccountInfoNationalAccountNumber> _nationalAccountNumber;
        
        /// <summary>
        /// <para xml:lang="en">Account number in free format.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("NationalAccountNumber")]
        public System.Collections.ObjectModel.Collection<HvzPaymentOrderDetailsStructureFirstOrderInfoAccountInfoNationalAccountNumber> NationalAccountNumber
        {
            get
            {
                return _nationalAccountNumber;
            }
            private set
            {
                _nationalAccountNumber = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the NationalAccountNumber collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NationalAccountNumberSpecified
        {
            get
            {
                return (this.NationalAccountNumber.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<HvzPaymentOrderDetailsStructureFirstOrderInfoAccountInfoBankCode> _bankCode;
        
        /// <summary>
        /// <para xml:lang="en">Bank sort code (German format or international as SWIFT-BIC).</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("BankCode")]
        public System.Collections.ObjectModel.Collection<HvzPaymentOrderDetailsStructureFirstOrderInfoAccountInfoBankCode> BankCode
        {
            get
            {
                return _bankCode;
            }
            private set
            {
                _bankCode = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the BankCode collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BankCodeSpecified
        {
            get
            {
                return (this.BankCode.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<HvzPaymentOrderDetailsStructureFirstOrderInfoAccountInfoNationalBankCode> _nationalBankCode;
        
        /// <summary>
        /// <para xml:lang="en">Bank sort code in free format.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("NationalBankCode")]
        public System.Collections.ObjectModel.Collection<HvzPaymentOrderDetailsStructureFirstOrderInfoAccountInfoNationalBankCode> NationalBankCode
        {
            get
            {
                return _nationalBankCode;
            }
            private set
            {
                _nationalBankCode = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the NationalBankCode collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NationalBankCodeSpecified
        {
            get
            {
                return (this.NationalBankCode.Count != 0);
            }
        }
    }
}
