//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H003
{
    
    
    /// <summary>
    /// <para xml:lang="en">Standard structure for HVZ OrderDetails related to payment orders</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    public partial interface IHvzPaymentOrderDetailsStructure
    {
        
        /// <summary>
        /// <para xml:lang="en">Total transaction number for all logical files (from dispay file).</para>
        /// </summary>
        string TotalOrders
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para xml:lang="en">Total transaction amount for all logical files (from dispay file).</para>
        /// <para xml:lang="en">Total number of digits: 24.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 4.</para>
        /// </summary>
        System.Nullable<decimal> TotalAmount
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para xml:lang="en">Order currency (only if identical across all transactions, ship otherwise).</para>
        /// <para xml:lang="en">Minimum length: 3. Maximum length: 3.</para>
        /// <para xml:lang="en">Pattern: [A-Z]{3}.</para>
        /// </summary>
        string Currency
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para xml:lang="en">Order details from display file for first logical file.</para>
        /// </summary>
        HvzPaymentOrderDetailsStructureFirstOrderInfo FirstOrderInfo
        {
            get;
            set;
        }
    }
}
