//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H003
{
    
    
    /// <summary>
    /// <para xml:lang="en">Attributes regarding the protocol version and revision of EBICS.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    public partial interface IVersionAttrGroup
    {
        
        /// <summary>
        /// <para xml:lang="en">Version of the EBICS protocol (e.g. "H003").</para>
        /// <para xml:lang="en">Minimum length: 4. Maximum length: 4.</para>
        /// <para xml:lang="en">Pattern: H\d{3}.</para>
        /// </summary>
        string Version
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para xml:lang="en">Revision of the EBICS protocol (e.g. 1).</para>
        /// <para xml:lang="en">Maximum inclusive value: 99.</para>
        /// </summary>
        System.Nullable<byte> Revision
        {
            get;
            set;
        }
    }
}
