//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H003
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("MutableHeaderTypeSegmentNumber", Namespace="http://www.ebics.org/H003")]
    public partial class MutableHeaderTypeSegmentNumber
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// <para xml:lang="en">Total number of digits: 10.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public ulong Value { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _lastSegment = false;
        
        /// <summary>
        /// <para xml:lang="en">Is this segment meant to be the last one regarding this transmission?</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlAttributeAttribute("lastSegment")]
        public bool LastSegment
        {
            get
            {
                return _lastSegment;
            }
            set
            {
                _lastSegment = value;
            }
        }
    }
}
