//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H003
{
    
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("PreValidationAccountAuthType", Namespace="http://www.ebics.org/H003")]
    public partial class PreValidationAccountAuthType : EBICO.Core.Schema.H003.AccountType
    {
        
        /// <summary>
        /// <para xml:lang="en">Total sum of the ordered payments regarding this account in order to check the maximum amount limit of the signature permission grades.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Amount")]
        public EBICO.Core.Schema.H003.AmountType Amount { get; set; }
    }
}
