//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H003
{
    
    
    /// <summary>
    /// <para xml:lang="en">Data type for pre-validation (request).</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("PreValidationRequestType", Namespace="http://www.ebics.org/H003")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EBICO.Core.Schema.H003.EbicsRequestBodyPreValidation))]
    public partial class PreValidationRequestType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<EBICO.Core.Schema.H003.DataDigestType> _dataDigest;
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("DataDigest")]
        public System.Collections.ObjectModel.Collection<EBICO.Core.Schema.H003.DataDigestType> DataDigest
        {
            get
            {
                return _dataDigest;
            }
            private set
            {
                _dataDigest = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the DataDigest collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataDigestSpecified
        {
            get
            {
                return (this.DataDigest.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PreValidationRequestType" /> class.</para>
        /// </summary>
        public PreValidationRequestType()
        {
            this._dataDigest = new System.Collections.ObjectModel.Collection<EBICO.Core.Schema.H003.DataDigestType>();
            this._accountAuthorisation = new System.Collections.ObjectModel.Collection<PreValidationAccountAuthType>();
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PreValidationAccountAuthType> _accountAuthorisation;
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("AccountAuthorisation")]
        public System.Collections.ObjectModel.Collection<PreValidationAccountAuthType> AccountAuthorisation
        {
            get
            {
                return _accountAuthorisation;
            }
            private set
            {
                _accountAuthorisation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AccountAuthorisation collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccountAuthorisationSpecified
        {
            get
            {
                return (this.AccountAuthorisation.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
    }
}
