//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H003
{
    
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("PubKeyDigestType", Namespace="http://www.ebics.org/H003")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataEncryptionInfoTypeEncryptionPubKeyDigest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EBICO.Core.Schema.H003.StaticHeaderTypeBankPubKeyDigestsAuthentication))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EBICO.Core.Schema.H003.StaticHeaderTypeBankPubKeyDigestsEncryption))]
    public partial class PubKeyDigestType
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Name of the used hash algorithm.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("Algorithm")]
        public string Algorithm { get; set; }
    }
}
