//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H003
{
    
    
    /// <summary>
    /// <para xml:lang="en">Data type for the static EBICS header.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("ResponseStaticHeaderType", Namespace="http://www.ebics.org/H003")]
    public partial class ResponseStaticHeaderType
    {
        
        /// <summary>
        /// <para xml:lang="en">unique transaction ID, provided by the server if and only if the order attribute is set to either "OZHNN" or "DZHNN" and if a transaction has been established actually.</para>
        /// <para xml:lang="en">Minimum length: 16. Maximum length: 16.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("TransactionID", DataType="hexBinary")]
        public byte[] TransactionId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Total number of segments for this transaction; mandatory for downloads in initialisation phase only.</para>
        /// <para xml:lang="en">Total number of digits: 10.</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("NumSegments")]
        public ulong NumSegmentsValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the NumSegments property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool NumSegmentsValueSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Total number of segments for this transaction; mandatory for downloads in initialisation phase only.</para>
        /// <para xml:lang="en">Total number of digits: 10.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<ulong> NumSegments
        {
            get
            {
                if (this.NumSegmentsValueSpecified)
                {
                    return this.NumSegmentsValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.NumSegmentsValue = value.GetValueOrDefault();
                this.NumSegmentsValueSpecified = value.HasValue;
            }
        }
    }
}
