//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H003
{
    
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("StaticHeaderBaseType", Namespace="http://www.ebics.org/H003")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NoPubKeyDigestsRequestStaticHeaderType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnsecuredRequestStaticHeaderType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnsignedRequestStaticHeaderType))]
    public abstract partial class StaticHeaderBaseType
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 35.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("HostID")]
        public string HostId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 16. Maximum length: 16.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Nonce", DataType="hexBinary")]
        public byte[] Nonce { get; set; }
        
        /// <summary>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("Timestamp", DataType="dateTime")]
        public System.DateTime TimestampValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Timestamp property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TimestampValueSpecified { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> Timestamp
        {
            get
            {
                if (this.TimestampValueSpecified)
                {
                    return this.TimestampValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TimestampValue = value.GetValueOrDefault();
                this.TimestampValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 35.</para>
        /// <para xml:lang="en">Pattern: [a-zA-Z0-9,=]{1,35}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("PartnerID")]
        public string PartnerId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 35.</para>
        /// <para xml:lang="en">Pattern: [a-zA-Z0-9,=]{1,35}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("UserID")]
        public string UserId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 35.</para>
        /// <para xml:lang="en">Pattern: [a-zA-Z0-9,=]{1,35}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("SystemID")]
        public string SystemId { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Product", IsNullable=true)]
        public ProductElementType Product { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderDetails")]
        public OrderDetailsType OrderDetails { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 4. Maximum length: 4.</para>
        /// <para xml:lang="en">Pattern: \d{4}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("SecurityMedium")]
        public string SecurityMedium { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="StaticHeaderBaseType" /> class.</para>
        /// </summary>
        public StaticHeaderBaseType()
        {
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
        }
    }
}
