//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0
namespace EBICO.Core.Schema.H003
{
    
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.Xml.Serialization.XmlTypeAttribute("UserPermissionType", Namespace="http://www.ebics.org/H003")]
    public partial class UserPermissionType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _orderTypes;
        
        /// <summary>
        /// <para xml:lang="en">List of order types which the user's permission belongs to.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("OrderTypes")]
        public System.Collections.ObjectModel.Collection<string> OrderTypes
        {
            get
            {
                return _orderTypes;
            }
            private set
            {
                _orderTypes = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="UserPermissionType" /> class.</para>
        /// </summary>
        public UserPermissionType()
        {
            this._orderTypes = new System.Collections.ObjectModel.Collection<string>();
            this._any = new System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement>();
            this._anyAttribute = new System.Collections.ObjectModel.Collection<System.Xml.XmlAttribute>();
        }
        
        /// <summary>
        /// <para xml:lang="en">Identification codes of the affected accounts.</para>
        /// <para xml:lang="en">Maximum length: 64.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("AccountID")]
        public string AccountId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum total amount which the user's permission is valid for.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("MaxAmount")]
        public EBICO.Core.Schema.H003.AmountType MaxAmount { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.Linq.XElement> Any
        {
            get
            {
                return _any;
            }
            private set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Authorization level of the user who signed the order; to be omitted for orders of type "download".</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlAttributeAttribute("AuthorisationLevel")]
        public EBICO.Core.Schema.H003.AuthorisationLevelType AuthorisationLevelValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the AuthorisationLevel property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool AuthorisationLevelValueSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Authorization level of the user who signed the order; to be omitted for orders of type "download".</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<EBICO.Core.Schema.H003.AuthorisationLevelType> AuthorisationLevel
        {
            get
            {
                if (this.AuthorisationLevelValueSpecified)
                {
                    return this.AuthorisationLevelValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.AuthorisationLevelValue = value.GetValueOrDefault();
                this.AuthorisationLevelValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<System.Xml.XmlAttribute> _anyAttribute;
        
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.XmlAttribute> AnyAttribute
        {
            get
            {
                return _anyAttribute;
            }
            private set
            {
                _anyAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnyAttribute collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnyAttributeSpecified
        {
            get
            {
                return (this.AnyAttribute.Count != 0);
            }
        }
    }
}
